In [1]:
import numpy as np

In [2]:
#(3*3)Matrix
A=np.array([[1,5,3],[4,6,6],[3,8,9]])
A

array([[1, 5, 3],
       [4, 6, 6],
       [3, 8, 9]])

In [3]:
#(3*4) Matrix
B=np.array([[1,5,3,4],[4,5,7,8],[7,8,9,3]])
B

array([[1, 5, 3, 4],
       [4, 5, 7, 8],
       [7, 8, 9, 3]])

In [4]:
#(3*1) matrix
C=np.array([[1],
             [4],
             [3]])

In [5]:
#(1*3) Matrix
D=np.array([[1,5,3]])

In [6]:
E=np.matmul(A,B)
print(E)

[[ 42  54  65  53]
 [ 70  98 108  82]
 [ 98 127 146 103]]


In [7]:
#A*B=(3*3)*(3*4)=(3*4)
#B*A=(3*4)*(3*3)=Not Legal
#A*C=(3*3)*(3*1)=(3*1)
#C*A=(3*1)*(3*3)=Not Legal
#C*D=(3*1)*(1*3)=(3*3)
#D*C=(1*3)*(3*1)=(1*1)

In [8]:
E=np.matmul(B,A)
print(E)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [9]:
E=np.matmul(A,C)
print(E)

[[30]
 [46]
 [62]]


In [10]:
E=np.matmul(C,A)
print(E)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [11]:
E=np.matmul(C,D)
print(E)

[[ 1  5  3]
 [ 4 20 12]
 [ 3 15  9]]


In [12]:
E=np.matmul(D,C)
print(E)

[[30]]
