In [1]:
import numpy as np

In [2]:
A=np.matrix([[0,1],[-2,-3]])
A

matrix([[ 0,  1],
        [-2, -3]])

In [3]:
B=np.matrix([[1,0],[3,-2]])
B

matrix([[ 1,  0],
        [ 3, -2]])

In [4]:
C=A+B
C

matrix([[ 1,  1],
        [ 1, -5]])

In [5]:
C=A-B
C

matrix([[-1,  1],
        [-5, -1]])

In [6]:
C=A*B
C

matrix([[  3,  -2],
        [-11,   6]])

In [7]:
#A+B=|0+1 1+0     |=|-1 1|
#    |-2+3 -3+(-2)| |1 -5|

#A+B=|0-1 1-0     |=|-1 1|
#    |-2-3 -3-(-2)| |5 -1|

#AB=|0*1+1*3   0*0+1*(-2)|=|3 -2|
#   |-2*1-3*3 -2*0-3*(-2)| |-11 6|

In [8]:
A=np.array([[0,1],[-2,-3]])
A

array([[ 0,  1],
       [-2, -3]])

In [9]:
B=np.array([[1,0],[3,-2]])
B

array([[ 1,  0],
       [ 3, -2]])

In [10]:
C=np.mat(A)*np.mat(B)
C

matrix([[  3,  -2],
        [-11,   6]])

In [11]:
C=A.dot(B)
C

array([[  3,  -2],
       [-11,   6]])

In [12]:
C=np.dot(A,B)
C

array([[  3,  -2],
       [-11,   6]])