In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
#x+2y=5
#3x+4y=6

A=np.array([[1,2],
           [3,4]])

In [3]:
b=np.array([[5],
           [6]])

In [4]:
Ainv=la.inv(A)
x=Ainv.dot(b)
print(x)

[[-4. ]
 [ 4.5]]


In [5]:
x=la.solve(A,b)
print(x)

[[-4. ]
 [ 4.5]]


In [6]:
#+2y=5
#x+4y=6
#7x+8y=9

A=np.array([[1,2],
            [3,4],
            [7,8]])
b=np.array([[5],[6],[9]])


x=la.lstsq(A,b,rcond=None)[0]
print(x)

[[-3.5       ]
 [ 4.17857143]]


In [7]:
A=np.array([[1,2,8,3],
            [3,4,5,6],
            [7,8,2,1]])
b=np.array([[5],[6],[9]])


x=la.lstsq(A,b,rcond=None)[0]
print(x)

[[0.49294612]
 [0.58899895]
 [0.40844965]
 [0.02048627]]


In [8]:
np.matmul(A[0],x)

array([5.])

In [9]:
np.matmul(A[1],x)

array([6.])

In [10]:
np.matmul(A[2],x)

array([9.])