In [1]:
import numpy as np

In [2]:
A=np.array([[1,3,7,2],
           [5,8,-9,0],
           [6,-7,11,12]])

In [3]:
B=np.array([[1,5],
           [4,5],
           [3,2],
           [7,8]])

In [4]:
print(A)

[[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]


In [5]:
Atr=np.transpose(A)
print(Atr)

[[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]


In [6]:
Btr=np.transpose(B)
print(Btr)

[[1 4 3 7]
 [5 5 2 8]]


In [7]:
import numpy.linalg as la

In [8]:
A=np.array([[1,2],
           [3,4]])

In [9]:
Adet=la.det(A)
print(Adet)

-2.0000000000000004


In [10]:
B=np.array([[-1,3,0],
           [2,1,-5],
           [1,4,-2]])

In [11]:
Bdet=la.det(B)
print(Bdet)

-21.00000000000001


In [12]:
Binv=la.inv(B)

In [13]:
print(Binv)

[[-0.85714286 -0.28571429  0.71428571]
 [ 0.04761905 -0.0952381   0.23809524]
 [-0.33333333 -0.33333333  0.33333333]]


In [14]:
Aeig=la.eig(A)
print(Aeig)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
