In [1]:
import pandas as pd 
import numpy as np
from sklearn import linear_model

In [2]:
df=pd.read_csv('C:\\Users\\nafissaad\\Tutorial\\Machine Learning\\Codebasics\\Machine Learning Tutorial Python 2-Linear Regression single Variable\\homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model =linear_model.LinearRegression()
model.fit(df[['area']].values,df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [6]:
model.predict([[5000]])

array([859554.79452055])

In [7]:
import pickle

In [8]:
#save model in pickle file
with open('model_pickle','wb') as f:#wb means in written in binary form
    pickle.dump(model,f)

In [9]:
#open save pickle file
with open('model_pickle','rb') as f:#rb means Read in binary form
    mp=pickle.load(f)

In [10]:
mp.predict([[5000]])

array([859554.79452055])

In [11]:
import joblib

In [12]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [13]:
mj=joblib.load('model_joblib')

In [14]:
mj.predict([[5000]])

array([859554.79452055])