In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('spam.csv')
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [4]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [5]:
def get_spam_number(x):
    if x=='spam':
        return 1
    return 0

In [6]:
df['spam']=df['Category'].apply(get_spam_number)#these two are essentially same
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [8]:
X_train.shape

(4457,)

In [9]:
X_test.shape

(1115,)

In [10]:
X_train[:4]

1727    ALRITE HUNNY!WOT U UP 2 2NITE? DIDNT END UP GO...
31      Yeah he got in at 2 and was v apologetic. n ha...
640     I had askd u a question some hours before. Its...
3495    You are being contacted by our dating service ...
Name: Message, dtype: object

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<4457x7695 sparse matrix of type '<class 'numpy.int64'>'
	with 59366 stored elements in Compressed Sparse Row format>

In [12]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [13]:
X_train_cv.shape

(4457, 7695)

In [14]:
v.get_feature_names_out()[10:30]

array(['021', '03', '04', '0430', '05', '050703', '0578', '06', '07',
       '07008009200', '07046744435', '07090201529', '07099833605',
       '07123456789', '0721072', '07734396839', '07742676969',
       '07753741225', '0776xxxxxxx', '07781482378'], dtype=object)

In [15]:
v.get_feature_names_out().shape#we have these many vocabulary in our sentence

(7695,)

In [16]:
dir(v)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',

In [17]:
v.vocabulary_

{'alrite': 908,
 'hunny': 3520,
 'wot': 7556,
 'up': 7136,
 '2nite': 393,
 'didnt': 2274,
 'end': 2554,
 'goin': 3134,
 'down': 2394,
 'town': 6954,
 'jus': 3836,
 'da': 2114,
 'pub': 5448,
 'instead': 3668,
 'chillin': 1774,
 'at': 1103,
 'mo': 4496,
 'in': 3608,
 'me': 4363,
 'bedroom': 1271,
 'love': 4183,
 'jen': 3776,
 'xxx': 7603,
 'yeah': 7628,
 'he': 3332,
 'got': 3161,
 'and': 946,
 'was': 7344,
 'apologetic': 998,
 'had': 3255,
 'fallen': 2729,
 'out': 4974,
 'she': 6037,
 'actin': 776,
 'like': 4069,
 'spoilt': 6353,
 'child': 1767,
 'caught': 1671,
 'that': 6766,
 'till': 6854,
 'but': 1560,
 'we': 7367,
 'won': 7523,
 'go': 3124,
 'there': 6790,
 'not': 4796,
 'doing': 2365,
 'too': 6925,
 'badly': 1183,
 'cheers': 1748,
 'you': 7657,
 'askd': 1079,
 'question': 5492,
 'some': 6256,
 'hours': 3481,
 'before': 1280,
 'its': 3731,
 'answer': 969,
 'are': 1034,
 'being': 1292,
 'contacted': 1958,
 'by': 1574,
 'our': 4971,
 'dating': 2147,
 'service': 5993,
 'someone': 6260,


In [18]:
v.get_feature_names_out()[7502]

'witin'

In [19]:
x_train_np=X_train_cv.toarray()
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [20]:
np.where(x_train_np[0]!=0)

(array([ 393,  908, 1103, 1271, 1774, 2114, 2274, 2394, 2554, 3134, 3520,
        3608, 3668, 3776, 3836, 4183, 4363, 4496, 5448, 6954, 7136, 7556,
        7603], dtype=int64),)

In [21]:
X_train[:4]

1727    ALRITE HUNNY!WOT U UP 2 2NITE? DIDNT END UP GO...
31      Yeah he got in at 2 and was v apologetic. n ha...
640     I had askd u a question some hours before. Its...
3495    You are being contacted by our dating service ...
Name: Message, dtype: object

In [23]:
X_train[:4][1727]

'ALRITE HUNNY!WOT U UP 2 2NITE? DIDNT END UP GOIN DOWN TOWN JUS DA PUB INSTEAD! JUS CHILLIN AT DA MO IN ME BEDROOM!LOVE JEN XXX.'

In [24]:
x_train_np[0][803]

0

In [25]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [26]:
X_test

846     Meanwhile in the shit suite: xavier decided to...
993     Up to ü... Ü wan come then come lor... But i d...
2421    Oic... Then better quickly go bathe n settle d...
2508                                               Yup...
4122                         Yunny... I'm goin to be late
                              ...                        
5519    Can you pls send me that company name. In saib...
1513    Hey sweet, I was wondering when you had a mome...
1429    Tell you what, if you make a little spreadshee...
2994                       So i'm doing a list of buyers.
3424    Had your mobile 10 mths? Update to latest Oran...
Name: Message, Length: 1115, dtype: object

In [27]:
x_test_cv=v.transform(X_test)
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [28]:
from sklearn.metrics import classification_report
y_pred=model.predict(x_test_cv)

In [29]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       971
           1       0.95      0.94      0.94       144

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [30]:
emails=[
    'Hey mohan, can we get togater to watch football game?',
    "Upto 20% discount on packing,exclusive offer just for you. Don't miss this reward"
]

In [31]:
emails_count=v.transform(emails)
model.predict(emails_count)#The first one is not a spam but the second is a spam 

array([0, 1], dtype=int64)

In [32]:
from sklearn.pipeline import Pipeline 
clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [33]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [34]:
print(classification_report(y_test,clf.predict(X_test)))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       971
           1       0.95      0.94      0.94       144

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

