In [1]:
import numpy as np
A=np.matrix([[6,5],[3,4]])
B=np.matrix([[49],[32]])
print(A)

[[6 5]
 [3 4]]


In [2]:
print(np.linalg.det(A))

8.999999999999998


In [3]:
print(np.linalg.inv(A))

[[ 0.44444444 -0.55555556]
 [-0.33333333  0.66666667]]


In [4]:
A.dot(np.linalg.inv(A))

matrix([[1., 0.],
        [0., 1.]])

In [5]:
Ai=A.copy()

In [6]:
Ai[:,0]=np.matrix([[49],[32]])
Ai

matrix([[49,  5],
        [32,  4]])

In [7]:
print(np.linalg.det(Ai))

36.000000000000014


In [8]:
xi=np.linalg.det(Ai)/np.linalg.det(A)

In [9]:
xi

4.000000000000003

In [10]:
Aii=A.copy()
Aii[:,1]=np.matrix([[49],[32]])
Aii

matrix([[ 6, 49],
        [ 3, 32]])

In [11]:
np.linalg.det(Aii)

44.99999999999999

In [12]:
xii=np.linalg.det(Aii)/np.linalg.det(A)

In [13]:
xii

5.0