In [63]:
import numpy as np
A=np.matrix([[1,1],[1,-3]])
B=np.matrix([[240],[0]])
print(A)

[[ 1  1]
 [ 1 -3]]


In [64]:
print(np.linalg.det(A))

-4.0


In [65]:
print(np.linalg.inv(A))

[[ 0.75  0.25]
 [ 0.25 -0.25]]


In [66]:
A_swp=np.swapaxes(A,1,0)

In [67]:
inv=np.linalg.inv(A)

In [68]:
inv.dot(B)

matrix([[180.],
        [ 60.]])