In [1]:
#Random
#Rand()

In [2]:
import numpy as np
var=np.random.rand(4)
print(var)

[0.18974923 0.98235025 0.88445542 0.4138264 ]


In [3]:
var1=np.random.rand(2,5)
print(var1)

[[0.06652561 0.44917653 0.68957588 0.34762712 0.02065125]
 [0.1286974  0.42962956 0.99468341 0.20181088 0.11083715]]


In [4]:
#Randn()
var2=np.random.randn(5)
print(var2)

[-0.79603291  0.37531073 -1.49345039  0.99478808  0.25001559]


In [5]:
#Randf() 0 included and 1 excluded range function
var3=np.random.ranf(4)
print(var3)

[0.94323159 0.21588509 0.20720886 0.517738  ]


In [6]:
#radint()
min_=5
max_=20
total_values=5
var4=np.random.randint(min_,max_,total_values)
print(var4)

[19 12  9 17  5]
