In [1]:
#Shape
import numpy as np
var=np.array([[1,2],[1,2]])
print(var,'\n')
print(var.shape)

[[1 2]
 [1 2]] 

(2, 2)


In [2]:
var=np.array([[1,2,3,4],[1,2,3,4]])
print(var,'\n')
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]] 

(2, 4)


In [3]:
var1=np.array([1,2,3,4],ndmin=4)
print(var1)
print(var1.ndim)
print(var1.shape)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


In [4]:
var2=np.array([1,2,3,4,5,6])
x=var2.reshape(3,2)
print(x)
print(x.ndim)
print(x.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [5]:
var2=np.array([1,2,3,4,5,6])
x=var2.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [6]:
var2=np.array([1,2,3,4,5,6,1,2,3])
x=var2.reshape(3,3)
print(x)
print(x.ndim)
print(x.shape)

[[1 2 3]
 [4 5 6]
 [1 2 3]]
2
(3, 3)


In [7]:
var2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=var2.reshape(2,3,2)
print(x)
print(x.ndim)
print(x.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


In [8]:
x=x.reshape(-1)
print(x)
print(x.ndim)
print(x.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)
