In [1]:
import numpy as np

In [2]:
var=np.array([1,2,3,4])
varadd=var+3
print(varadd)

[4 5 6 7]


In [3]:
var1=np.array([1,2,3,4])
varadd=var+var1
print(varadd)

[2 4 6 8]


In [4]:
var=np.array([1,2,3,4])
varadd=var-3
print(varadd)

[-2 -1  0  1]


In [5]:
var=np.array([1,2,3,4])
varadd=var/3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [6]:
var=np.array([1,2,3,4])
varadd=var*3
print(varadd)

[ 3  6  9 12]


In [7]:
var=np.array([1,2,3,4])
varadd=var%3#moduler Remider of diving two number
print(varadd)

[1 2 0 1]


In [8]:
np.add(var,3)

array([4, 5, 6, 7])

In [9]:
np.subtract(var,3)

array([-2, -1,  0,  1])

In [10]:
np.multiply(var,3)

array([ 3,  6,  9, 12])

In [11]:
np.divide(var,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [12]:
np.power(var,var1)

array([  1,   4,  27, 256], dtype=int32)

In [13]:
np.reciprocal(var,var1)

array([1, 0, 0, 0])

In [14]:
#2D array
var=np.array([[1,2,3,4],[1,2,3,4]])
var1=np.array([[1,2,3,4],[1,2,3,4]])

varadd=var+var1
print(varadd)

[[2 4 6 8]
 [2 4 6 8]]


In [15]:
np.reciprocal(var)

array([[1, 0, 0, 0],
       [1, 0, 0, 0]], dtype=int32)

In [16]:
var=np.array([1,2,3,4,5,3,2])
print('min :',np.min(var))
print('max :',np.max(var))

min : 1
max : 5


In [17]:
var=np.array([[1,2,3,4],[1,2,3,6]])
print('min :',np.min(var))
print('max :',np.max(var))

min : 1
max : 6


In [18]:
var=np.array([[1,2,3,4],[1,2,6,3]])
print('min :',np.min(var),np.argmin(var))
print('max :',np.max(var),np.argmax(var))

min : 1 0
max : 6 6


In [19]:
var=np.array([[1,2,3,4],[4,8,6,9]])
print('min :',np.min(var,axis=1))#row wise
print('min :',np.min(var,axis=0))#column wise
print('Sqrt :',np.sqrt(var))#column wise

min : [1 4]
min : [1 2 3 4]
Sqrt : [[1.         1.41421356 1.73205081 2.        ]
 [2.         2.82842712 2.44948974 3.        ]]


In [20]:
var=np.array([1,2,3,4,5,3,2])
print(np.sin(var))
print(np.cos(var))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427  0.14112001
  0.90929743]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219 -0.9899925
 -0.41614684]


In [21]:
var=np.array([1,2,3,4,5,3,2])
np.cumsum(var)

array([ 1,  3,  6, 10, 15, 18, 20], dtype=int32)