In [1]:
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
print( var1+var2 )

[2 4 6 8]


In [2]:
var1.shape

(4,)

In [3]:
var2=np.array([[1],[2],[3],[4]])
print(var2)
var2.shape

[[1]
 [2]
 [3]
 [4]]


(4, 1)

In [4]:
print(var1+var2)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [5]:
x=np.array([[1],[2]])
print(x.shape)

(2, 1)


In [6]:
y=np.array([[1,2,3],[1,2,3]])
print(y.shape)

(2, 3)


In [7]:
print(x+y)

[[2 3 4]
 [3 4 5]]


In [8]:
#indexing
var=np.array([9,8,7,6])
#             0,1,2,3
#            -4,-3,-2,-1
print(var[1])
print(var[-1])

8
6


In [9]:
var1=np.array([[9,8,7],[4,5,6]])
print(var1)
print(var1.ndim)

[[9 8 7]
 [4 5 6]]
2


In [10]:
print(var1[1,0])

4


In [11]:
var2=np.array([[[1,2,7],[1,2,9]]
              ,[[4,5,8],[4,6,9]]])
print(var2)

[[[1 2 7]
  [1 2 9]]

 [[4 5 8]
  [4 6 9]]]


In [12]:
print(var2[1,1,1])
print(var2[1,0:])
print(var2[1,0,1:2])

6
[[4 5 8]
 [4 6 9]]
[5]


In [13]:
#Slicing
var=np.array([1,2,3,4,5,6,7])
print(var)

[1 2 3 4 5 6 7]


In [14]:
print('2 to 5 :',var[1:5])
print('2 to end :',var[1:])
print('start to 5 :',var[:5])
print('stop :',var[1:6:2])
print('stop :',var[::2])
print('stop :',var[0:6:2])

2 to 5 : [2 3 4 5]
2 to end : [2 3 4 5 6 7]
start to 5 : [1 2 3 4 5]
stop : [2 4 6]
stop : [1 3 5 7]
stop : [1 3 5]
