In [1]:
import numpy as np
var=np.array([9,8,7,6,5,4])
for i in var:
    print(i)

9
8
7
6
5
4


In [2]:
var1=np.array([[1,2,3,4],[1,2,3,4]])
print(var1)

[[1 2 3 4]
 [1 2 3 4]]


In [3]:
for j in var1:
    print(j)

[1 2 3 4]
[1 2 3 4]


In [4]:
for j in var1:
    for k in j:
        print(k)

1
2
3
4
1
2
3
4


In [5]:
var3=np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)

[[[1 2 3 4]
  [1 2 3 4]]]


In [6]:
print(var3.ndim)

3


In [7]:
for i in var3:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
1
2
3
4


In [8]:
for i in np.nditer(var3):
    print(i)

1
2
3
4
1
2
3
4


In [9]:
for i in np.nditer(var3,flags=['buffered'],op_dtypes=['S']):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'1'
b'2'
b'3'
b'4'


In [10]:
var3=np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i in np.ndenumerate(var3):
    print(i)

[[[9 8 7 6]
  [1 2 3 4]]]
3

((0, 0, 0), 9)
((0, 0, 1), 8)
((0, 0, 2), 7)
((0, 0, 3), 6)
((0, 1, 0), 1)
((0, 1, 1), 2)
((0, 1, 2), 3)
((0, 1, 3), 4)


In [11]:
var=np.array([1,2,3,4])
co=var.copy()
print('var :',var)
print('copy ',co)

var : [1 2 3 4]
copy  [1 2 3 4]


In [12]:
vi=var.view()
print('var :',var)
print('view :',vi)

var : [1 2 3 4]
view : [1 2 3 4]


In [13]:
co[1]=40
print('var :',var)
vi[1]=40
print('var :',var)

var : [1 2 3 4]
var : [ 1 40  3  4]


In [14]:
import numpy as np
var=np.array([1,2,3,4])
var1=np.array([9,8,7,6])
ar=np.concatenate((var,var1))
print(ar)

[1 2 3 4 9 8 7 6]


In [15]:
var=np.array([[1,2],[3,4]])
var1=np.array([[9,8],[7,6]])
ar=np.concatenate((var,var1),axis=1)
print(var)
print()
print(var1)
print(ar)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]
[[1 2 9 8]
 [3 4 7 6]]


In [16]:
var=np.array([[1,2],[3,4]])
var1=np.array([[9,8],[7,6]])
ar=np.concatenate((var,var1),axis=0)
print(var)
print()
print(var1)
print(ar)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]
[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [17]:
var=np.array([1,2,3,4])
var1=np.array([9,8,7,6])
ar=np.stack((var,var1),axis=1)
print(ar)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]


In [18]:
var=np.array([1,2,3,4])
var1=np.array([9,8,7,6])
ar=np.stack((var,var1),axis=0)
print(ar)

[[1 2 3 4]
 [9 8 7 6]]


In [19]:
var=np.array([1,2,3,4])
var1=np.array([9,8,7,6])
ar=np.hstack((var,var1))
print(ar)

[1 2 3 4 9 8 7 6]


In [20]:
var=np.array([1,2,3,4])
var1=np.array([9,8,7,6])
ar=np.vstack((var,var1))
print(ar)

[[1 2 3 4]
 [9 8 7 6]]


In [21]:
var=np.array([1,2,3,4])
var1=np.array([9,8,7,6])
ar=np.dstack((var,var1))
print(ar)

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [22]:
var=np.array([1,2,3,4,5,6])
print(var)
ar=np.array_split(var,3)
print()
print(ar)
print(ar[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [23]:
var=np.array([[1,2],[3,4],[5,6]])
print(var)
ar=np.array_split(var,3)
print()
print(ar)
print(ar[0])

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[[1 2]]


In [24]:
var=np.array([[1,2],[3,4],[5,6]])
print(var)
ar=np.array_split(var,2,axis=1)
print()
print(ar)
print(ar[0])

[[1 2]
 [3 4]
 [5 6]]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]
[[1]
 [3]
 [5]]


In [25]:
var=np.array([[1,2],[3,4],[5,6]])
print(var)
ar=np.array_split(var,3,axis=0)
print()
print(ar)
print(ar[0])

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[[1 2]]
