In [1]:
import numpy as np
var=np.array([1,2,3,4,2,5,2,5,6,7])
#index        0,1,2,3,4,5,6,7,8,9

#position index
x=np.where(var==2)
x

(array([1, 4, 6], dtype=int64),)

In [2]:
x=np.where(var/2==2)
x

(array([3], dtype=int64),)

In [3]:
x=np.where((var%2)==0)
x

(array([1, 3, 4, 6, 8], dtype=int64),)

In [4]:
#Search Shorted
var1=np.array([1,2,3,4,5,6,7,8])
#index         0,1,2,3,4,5,6,7

x1=np.searchsorted(var1,5,side='right')
print(x1)

5


In [5]:
#Replace
var1=np.array([1,2,3,4,9,10])
#index         0,1,2,3,4,5

x1=np.searchsorted(var1,[5,6,7],side='right')
print(x1)

[4 4 4]


In [6]:
var1

array([ 1,  2,  3,  4,  9, 10])

In [7]:
#sort
var_1=np.array([4,2,3,1,12,5,22,52,6,7])

print(np.sort(var_1))

[ 1  2  3  4  5  6  7 12 22 52]


In [8]:
#sort
var_1=np.array([[4,2,3],[1,12,5],[22,52,6]])

print(np.sort(var_1))

[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


In [9]:
var_1=np.array(['a','s','d','f'])

print(np.sort(var_1))

['a' 'd' 'f' 's']


In [10]:
var_1=np.array(['a','s','d','f'])
f=[True,False,False,True]
new_a=var_1[f]
print(new_a)

['a' 'f']
