In [1]:
#Shuffle
import numpy as np

var=np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[2 1 5 4 3]


In [2]:
#Unique
var1=np.array([1,2,3,4,2,5,5,6,7])
x=np.unique(var1)
x

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
#Unique
var1=np.array([1,2,3,4,2,5,5,6,7])
x=np.unique(var1,return_index=True,return_counts=True)#index number counting 
x

(array([1, 2, 3, 4, 5, 6, 7]),
 array([0, 1, 2, 3, 5, 7, 8], dtype=int64),
 array([1, 2, 1, 1, 2, 1, 1], dtype=int64))

In [4]:
#Unique
var1=np.array([1,2,3,4,2,5,5,6,7])
x=np.unique(var1,return_index=True)#index number
x

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 8], dtype=int64))

In [5]:
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [6]:
#Flatten
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y)
print(y.flatten())
print(y.ravel())

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [7]:
#Flatten
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y)
print(y.flatten(order='F'))
print(y.ravel())

[[1 2]
 [3 4]
 [5 6]]
[1 3 5 2 4 6]
[1 2 3 4 5 6]


In [8]:
print(y.flatten(order='A'))

[1 2 3 4 5 6]


In [9]:
print(y.flatten(order='k'))

[1 2 3 4 5 6]
