In [21]:
import numpy as np
x=np.array([1,2,3,4])
print(type(x))
print(x)

<class 'numpy.ndarray'>
[1 2 3 4]


In [22]:
y=[1,2,3,4]
print(type(y))
print(y)

<class 'list'>
[1, 2, 3, 4]


In [23]:
%timeit [j**4 for j in range(1,9)]

4.43 µs ± 54.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [24]:
%timeit np.arange(1,9)**4

3.26 µs ± 88.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [25]:
x=[1,2,3,4]
y=np.array([1,2,3,4,5])
y

array([1, 2, 3, 4, 5])

In [26]:
l=[]
for i in range(1,5):
    int_1=input('endet: ')
    l.append(int_1)
print(np.array(l))

endet: 12
endet: 12
endet: 15
endet: 16
['12' '12' '15' '16']


In [27]:
l=[]
for i in range(1,5):
    int_1=int(input('endet: '))
    l.append(int_1)
print(np.array(l))

endet: 12
endet: 154
endet: 18
endet: 14
[ 12 154  18  14]


In [28]:
y.ndim#to know the dimension

1

In [29]:
ar2=np.array([[1,2,3,4],[1,2,3,]])
print(ar2)#both data has to be same size, other wise it will create 1 dimension list

[list([1, 2, 3, 4]) list([1, 2, 3])]


C:\Users\nafissaad\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [30]:
ar2=np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [32]:
ar3=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [35]:
#create multi dimension array
arn=np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
