In [1]:
import numpy as np
var=np.array([1,2,3,4])
print(var)

[1 2 3 4]


In [2]:
v=np.insert(var,2,40)
print(v)

[ 1  2 40  3  4]


In [3]:
v=np.insert(var,(2,4),4.5)
print(v)

[1 2 4 3 4 4]


In [6]:
var1=np.array([[1,2,3],[1,2,3]])
v1=np.insert(var1,2,6.5,axis=0)

In [7]:
print(v1)

[[1 2 3]
 [1 2 3]
 [6 6 6]]


In [8]:
var1=np.array([[1,2,3],[1,2,3]])
v1=np.insert(var1,2,6.5,axis=1)

In [9]:
print(v1)

[[1 2 6 3]
 [1 2 6 3]]


In [10]:
var1=np.array([[1,2,3],[1,2,3]])
v1=np.insert(var1,2,[22,23],axis=1)

In [11]:
print(v1)

[[ 1  2 22  3]
 [ 1  2 23  3]]


In [13]:
var1=np.array([[1,2,3],[1,2,3]])
v1=np.insert(var1,2,[22,23,25],axis=0)

In [14]:
print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [22 23 25]]


In [16]:
var1=np.array([[1,2,3],[1,2,3]])
v1=np.append(var1,[[22,23,25]],axis=0)

In [17]:
print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [22 23 25]]


In [18]:
var1=np.array([1,2,3,4])
d=np.delete(var1,2)
print(d)

[1 2 4]
