In [1]:
import numpy as np
v=np.matrix([[1,2],[1,2]])
v1=np.matrix([[1,2],[1,2]])
print(type(v))#class is matrix not a array

<class 'numpy.matrix'>


In [2]:
v.dot(v1)#Multiplication

matrix([[3, 6],
        [3, 6]])

In [3]:
v*v1

matrix([[3, 6],
        [3, 6]])

In [4]:
var=np.matrix([[1,2,3],[4,5,6]])
print(var)

[[1 2 3]
 [4 5 6]]


In [5]:
print(np.transpose(var))

[[1 4]
 [2 5]
 [3 6]]


In [6]:
print(var.T)

[[1 4]
 [2 5]
 [3 6]]


In [7]:
print(np.swapaxes(var,0,1))

[[1 4]
 [2 5]
 [3 6]]


In [8]:
var2=np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [9]:
#Inverse matrix
var2=np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.linalg.inv(var2))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
np.linalg.inv(var2)*var2

matrix([[1.00000000e+00, 0.00000000e+00],
        [2.22044605e-16, 1.00000000e+00]])

In [11]:
#power
print(np.linalg.matrix_power(var2,2))
print()

#Indentity matrix
print(np.linalg.matrix_power(var2,0))
print()

print(np.linalg.matrix_power(var2,-2))

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [12]:
var5=np.matrix([[1,2],[4,5]])
print(var5)
print()
print(np.linalg.det(var5))

[[1 2]
 [4 5]]

-2.9999999999999996


In [13]:
var5=np.matrix([[1,2,3],[4,5,6],[1,2,3]])
print(var5)
print()
print(np.linalg.det(var5))

[[1 2 3]
 [4 5 6]
 [1 2 3]]

0.0
