In [2]:
#Zeros
import numpy as np

ar_zeros=np.zeros(4)
print(ar_zeros)

[0. 0. 0. 0.]


In [4]:
#Create two dimension array
ar_zeros1=np.zeros((3,4))
print(ar_zeros1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#Ones
ar_one=np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [6]:
#Create an empty array
ar_em=np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [7]:
#Range array
ar_rn=np.arange(4)
print(ar_rn)

[0 1 2 3]


In [8]:
#identity matrix
#diagonal
ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
ar_dia=np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [10]:
#linespace
ar_lin=np.linspace(1,10,num=5)
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]
