In [1]:
import numpy as np
import time 
import sys

In [2]:
size=10000

In [3]:
l1=range(size)
l2=range(size)

In [4]:
a1=np.arange(size)
a2=np.arange(size)

In [5]:
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print('Python list took: ',(time.time()-start)*1000)

Python list took:  2.002239227294922


In [6]:
start=time.time()
result=a1+a2
print('Python list took: ',(time.time()-start)*1000)

Python list took:  0.0


In [7]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1+a2

array([5, 7, 9])

In [8]:
a2-a1

array([3, 3, 3])

In [9]:
a1*a2

array([ 4, 10, 18])

In [10]:
a1/a2

array([0.25, 0.4 , 0.5 ])