In [1]:
import numpy as np

In [2]:
a=np.array([5,6,9])
a[0]
a[1]

6

In [3]:
a.ndim

1

In [4]:
a=np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [5]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
a.itemsize

8

In [6]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [7]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.int64)
a.itemsize

8

In [8]:
a

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int64)

In [9]:
a.size

6

In [10]:
a.shape

(3, 2)

In [11]:
a=np.array([[1,2],[3,4],[5,6]],dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [12]:
a=np.array([[1,2],[3,4],[5,6]])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.arange(1,5)

array([1, 2, 3, 4])

In [16]:
np.arange(1,5,2)

array([1, 3])

In [17]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [18]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [19]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [20]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
a.min()

1

In [22]:
a.max()

6

In [23]:
a.sum(axis=0)

array([ 9, 12])

In [24]:
a.sum(axis=1)

array([ 3,  7, 11])

In [25]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [26]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
np.std(a)

1.707825127659933

In [28]:
b=np.array([[5,6],[7,8],[9,10]])
b

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [29]:
a+b

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [30]:
a*b

array([[ 5, 12],
       [21, 32],
       [45, 60]])

In [31]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ],
       [0.55555556, 0.6       ]])

In [32]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [33]:
a.dot(b)

array([46, 52])

In [34]:
(1*5)+(2*7)+(3*9)

46