In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame()
df['Company']=['Iphone','IPad','Mac']
df['2018']=[180,24,12]
df['2019']=[200,36,18]
df['2020']=[220,40,20]
df.set_index('Company',inplace=True)

In [3]:
df1=pd.DataFrame()
df1['Company']=['Iphone','IPad','Mac']
df1['2018']=[80,10,8]
df1['2019']=[90,16,10]
df1['2020']=[100,20,10]
df1.set_index('Company',inplace=True)

In [4]:
df,df1

(         2018  2019  2020
 Company                  
 Iphone    180   200   220
 IPad       24    36    40
 Mac        12    18    20,
          2018  2019  2020
 Company                  
 Iphone     80    90   100
 IPad       10    16    20
 Mac         8    10    10)

In [5]:
revenue=np.array(df[['2018', '2019', '2020']].values)
expense=np.array(df1.values)
revenue

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]], dtype=int64)

In [6]:
profit=revenue-expense
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]], dtype=int64)

In [7]:
profit= pd.DataFrame(profit,index=df.index,columns=['2018', '2019','2020'])
profit

2018  2019  2020
Company                  
Iphone    100   110   120
IPad       14    20    20
Mac         4     8    10

In [8]:
Units=pd.DataFrame()
Units['Company']=['Iphone','IPad','Mac']
Units['2018']=[30,5,2]
Units['2019']=[40,10,5]
Units['2020']=[50,15,7]
Units.set_index('Company',inplace=True)

In [9]:
per_price=pd.DataFrame()
per_price['Company']=['Iphone','IPad','Mac']
per_price['Price Per Unit']=[1000,400,1200]
per_price.set_index('Company',inplace=True)


In [10]:
per_price=np.array(per_price['Price Per Unit'].values)
Units=np.array(Units.values)
Units,per_price

(array([[30, 40, 50],
        [ 5, 10, 15],
        [ 2,  5,  7]], dtype=int64),
 array([1000,  400, 1200], dtype=int64))

In [11]:
Units*per_price

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]], dtype=int64)

In [12]:
np.dot(per_price,Units)

array([34400, 50000, 64400], dtype=int64)