In [1]:
import numpy as np
y_predict=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [2]:
def Mse(y_true,y_predict):
    total_error=0
    for yt,yp in zip(y_true,y_predict):
        print(yt,yp)

In [3]:
Mse(y_true,y_predict)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1


In [4]:
def Mse(y_true,y_predict):
    total_error=0
    for yt,yp in zip(y_true,y_predict):
        total_error += abs(yt-yp)#calculating error and sum it up at each itration
    print('Total Error',total_error)
    mse=total_error/len(y_true)#both the array has same length 2
    print('Mse:',mse)
    return mse

In [5]:
Mse(y_true,y_predict)

Total Error 2.5
Mse: 0.5


0.5

In [6]:
#numpy can do the same with its vector propertird
y_predict-y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [7]:
np.abs(y_predict-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [8]:
np.mean(np.abs(y_predict-y_true))#just one line of code to excecute whole process

0.5

In [9]:
np.log([0.00000000001])

array([-25.32843602])

In [10]:
def log_loss(y_true,y_predict):#log_loss work well for binary classification 
    epsilon=1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predict]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [11]:
log_loss(y_true, y_predict)

17.2696280766844