In [44]:
import random
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import math
import scipy.stats as stats
from scipy.stats import norm
from scipy.stats import kurtosis
import requests
%matplotlib inline

In [45]:
df=pd.read_excel('C:\\Users\\nafissaad\\Downloads\\NEDL_Maximum_Decorrelation_Portfolio.xlsx',index_col='Unnamed: 0')[['AAPL','CAT','CVX','JPM','WMT']]
#Boudoukh, Richardson, and Whitelaw (1997)
df

AAPL         CAT         CVX         JPM         WMT
2011-12-30   12.350067   67.297470   68.593330   24.464430   46.885895
2012-01-03   12.540050   69.808136   71.152679   25.737314   47.333115
2012-01-04   12.607438   70.454361   71.030167   25.900354   46.846676
2012-01-05   12.747407   70.952034   70.333946   26.441336   46.619144
2012-01-06   12.880666   71.130318   69.824631   26.204182   46.289627
...                ...         ...         ...         ...         ...
2021-12-27  179.586868  202.989365  115.546700  153.320740  139.104004
2021-12-28  178.551147  203.225418  115.322968  153.786026  141.100235
2021-12-29  178.640778  203.923752  114.729622  153.708481  141.031082
2021-12-30  177.465637  202.694290  114.223824  153.630920  141.485657
2021-12-31  176.838242  203.343445  114.146004  153.504913  142.987793

[2518 rows x 5 columns]

In [46]:
returns=df.pct_change()
returns

AAPL       CAT       CVX       JPM       WMT
2011-12-30       NaN       NaN       NaN       NaN       NaN
2012-01-03  0.015383  0.037307  0.037312  0.052030  0.009538
2012-01-04  0.005374  0.009257 -0.001722  0.006335 -0.010277
2012-01-05  0.011102  0.007064 -0.009802  0.020887 -0.004857
2012-01-06  0.010454  0.002513 -0.007241 -0.008969 -0.007068
...              ...       ...       ...       ...       ...
2021-12-27  0.022975  0.000873  0.020445  0.005723  0.009105
2021-12-28 -0.005767  0.001163 -0.001936  0.003035  0.014351
2021-12-29  0.000502  0.003436 -0.005145 -0.000504 -0.000490
2021-12-30 -0.006578 -0.006029 -0.004409 -0.000505  0.003223
2021-12-31 -0.003535  0.003203 -0.000681 -0.000820  0.010617

[2518 rows x 5 columns]

In [47]:
Corretion=returns.corr()
Corretion

AAPL       CAT       CVX       JPM       WMT
AAPL  1.000000  0.381805  0.340409  0.382334  0.293197
CAT   0.381805  1.000000  0.573065  0.603777  0.250414
CVX   0.340409  0.573065  1.000000  0.632493  0.219925
JPM   0.382334  0.603777  0.632493  1.000000  0.271739
WMT   0.293197  0.250414  0.219925  0.271739  1.000000

In [48]:
weights=np.array([1/5 for i in range(5)])
weights

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [49]:
Synthetic_correlation=(weights.dot(Corretion)).dot(weights.T)
Synthetic_correlation

0.5159326287620143

In [50]:
Invers_cov=pd.DataFrame(np.linalg.inv(Corretion))
Invers_cov.columns=df.columns
Invers_cov.index=df.columns
Invers_cov

AAPL       CAT       CVX       JPM       WMT
AAPL  1.278193 -0.237135 -0.115796 -0.208926 -0.233141
CAT  -0.237135  1.801274 -0.527651 -0.638145 -0.092084
CVX  -0.115796 -0.527651  1.855844 -0.804587 -0.023428
JPM  -0.208926 -0.638145 -0.804587  2.014687 -0.149463
WMT  -0.233141 -0.092084 -0.023428 -0.149463  1.137183

In [51]:
One_=np.array([1 for i in range(5)])
One_

array([1, 1, 1, 1, 1])

In [54]:
One_.dot(Invers_cov)

array([0.48319472, 0.30625945, 0.38438301, 0.21356694, 0.63906712])

In [55]:
sum(One_.dot(Invers_cov))

2.026471243419031

In [56]:
One_.dot(Invers_cov)/sum(One_.dot(Invers_cov))

array([0.23844144, 0.15112943, 0.18968096, 0.10538859, 0.31535958])