In [1]:
import random
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import math
import scipy.stats as stats
from scipy.stats import norm
from scipy.stats import kurtosis
import requests
%matplotlib inline

In [2]:
df=pd.read_excel('C:\\Users\\nafissaad\\Downloads\\NEDL_PMPT.xlsx',skiprows=[0],index_col='Unnamed: 0')[['JPM','WMT','MSFT','KO','PFE','CAT','SP 500']]
#df.to_excel('C:\\Users\\nafissaad\\Downloads\\NEDL_PMPT.xlsx')
df

JPM         WMT        MSFT         KO        PFE  \
2011-11-14   24.705299   46.650124   21.537199  24.791821  13.043631   
2011-11-15   24.819157   45.517323   21.683163  24.868612  13.096357   
2011-11-16   23.885593   44.899456   21.139864  24.506557  12.898625   
2011-11-17   23.141773   44.939053   20.710085  24.363930  12.832716   
2011-11-18   23.240440   45.335125   20.515478  24.645535  12.872263   
...                ...         ...         ...        ...        ...   
2021-11-08  169.059998  149.270004  336.989990  56.330002  48.330002   
2021-11-09  167.779999  149.789993  335.950012  56.490002  47.299999   
2021-11-10  167.619995  148.440002  330.799988  56.720001  49.020000   
2021-11-11  167.610001  148.500000  332.429993  56.740002  50.180000   
2021-11-12  166.860001  147.759995  336.720001  56.610001  49.730000   

                   CAT      SP 500  
2011-11-14   72.899940  103.301254  
2011-11-15   73.307755  103.811737  
2011-11-16   72.310883  102.164955  
2011-11-17   70.845764  100.542900  
2011-11-18   70.936417  100.435875  
...                ...         ...  
2021-11-08  214.250000  468.929993  
2021-11-09  209.809998  467.380005  
2021-11-10  206.669998  463.619995  
2021-11-11  208.529999  463.769989  
2021-11-12  209.270004  467.269989  

[2517 rows x 7 columns]

In [3]:
#CShalit and Yitzhaki 1984 showed GINI cofficient can be generalized as trated as measure of risk
returns=df.pct_change().fillna(0)
returns

JPM       WMT      MSFT        KO       PFE       CAT  \
2011-11-14  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2011-11-15  0.004609 -0.024283  0.006777  0.003097  0.004042  0.005594   
2011-11-16 -0.037615 -0.013574 -0.025056 -0.014559 -0.015098 -0.013598   
2011-11-17 -0.031141  0.000882 -0.020330 -0.005820 -0.005110 -0.020261   
2011-11-18  0.004264  0.008814 -0.009397  0.011558  0.003082  0.001280   
...              ...       ...       ...       ...       ...       ...   
2021-11-08  0.006010 -0.006390  0.002767 -0.008973 -0.005760  0.040655   
2021-11-09 -0.007571  0.003484 -0.003086  0.002840 -0.021312 -0.020723   
2021-11-10 -0.000954 -0.009013 -0.015330  0.004072  0.036364 -0.014966   
2021-11-11 -0.000060  0.000404  0.004927  0.000353  0.023664  0.009000   
2021-11-12 -0.004475 -0.004983  0.012905 -0.002291 -0.008968  0.003549   

              SP 500  
2011-11-14  0.000000  
2011-11-15  0.004942  
2011-11-16 -0.015863  
2011-11-17 -0.015877  
2011-11-18 -0.001064  
...              ...  
2021-11-08  0.000854  
2021-11-09 -0.003305  
2021-11-10 -0.008045  
2021-11-11  0.000324  
2021-11-12  0.007547  

[2517 rows x 7 columns]

In [4]:
matrix=pd.DataFrame(columns=[['JPM','WMT','MSFT','KO','PFE','CAT']],index=['Returns,historical'])
matrix

JPM  WMT MSFT   KO  PFE  CAT
Returns,historical  NaN  NaN  NaN  NaN  NaN  NaN

In [5]:
matrix.loc['Returns,historical']=[((df[i][-1]/df[i][0])**(1/10)-1) for i in df.columns[:-1]]
matrix

JPM     WMT      MSFT        KO       PFE       CAT
Returns,historical  0.210476  0.1222  0.316461  0.086072  0.143199  0.111215

In [6]:
matrix.loc['Weights']=1/len(df.columns[:-1])
matrix

JPM       WMT      MSFT        KO       PFE       CAT
Returns,historical  0.210476    0.1222  0.316461  0.086072  0.143199  0.111215
Weights             0.166667  0.166667  0.166667  0.166667  0.166667  0.166667

In [7]:
df['Portfolio']=matrix.loc['Weights'].values.dot(returns[df.columns[:-1]].values.T)
df

JPM         WMT        MSFT         KO        PFE  \
2011-11-14   24.705299   46.650124   21.537199  24.791821  13.043631   
2011-11-15   24.819157   45.517323   21.683163  24.868612  13.096357   
2011-11-16   23.885593   44.899456   21.139864  24.506557  12.898625   
2011-11-17   23.141773   44.939053   20.710085  24.363930  12.832716   
2011-11-18   23.240440   45.335125   20.515478  24.645535  12.872263   
...                ...         ...         ...        ...        ...   
2021-11-08  169.059998  149.270004  336.989990  56.330002  48.330002   
2021-11-09  167.779999  149.789993  335.950012  56.490002  47.299999   
2021-11-10  167.619995  148.440002  330.799988  56.720001  49.020000   
2021-11-11  167.610001  148.500000  332.429993  56.740002  50.180000   
2021-11-12  166.860001  147.759995  336.720001  56.610001  49.730000   

                   CAT      SP 500 Portfolio  
2011-11-14   72.899940  103.301254       0.0  
2011-11-15   73.307755  103.811737 -0.000027  
2011-11-16   72.310883  102.164955 -0.019917  
2011-11-17   70.845764  100.542900  -0.01363  
2011-11-18   70.936417  100.435875  0.003267  
...                ...         ...       ...  
2021-11-08  214.250000  468.929993  0.004718  
2021-11-09  209.809998  467.380005 -0.007728  
2021-11-10  206.669998  463.619995  0.000029  
2021-11-11  208.529999  463.769989  0.006381  
2021-11-12  209.270004  467.269989 -0.000711  

[2517 rows x 8 columns]

In [8]:
df['Rank']=[i for i in range(len(df))]
df

JPM         WMT        MSFT         KO        PFE  \
2011-11-14   24.705299   46.650124   21.537199  24.791821  13.043631   
2011-11-15   24.819157   45.517323   21.683163  24.868612  13.096357   
2011-11-16   23.885593   44.899456   21.139864  24.506557  12.898625   
2011-11-17   23.141773   44.939053   20.710085  24.363930  12.832716   
2011-11-18   23.240440   45.335125   20.515478  24.645535  12.872263   
...                ...         ...         ...        ...        ...   
2021-11-08  169.059998  149.270004  336.989990  56.330002  48.330002   
2021-11-09  167.779999  149.789993  335.950012  56.490002  47.299999   
2021-11-10  167.619995  148.440002  330.799988  56.720001  49.020000   
2021-11-11  167.610001  148.500000  332.429993  56.740002  50.180000   
2021-11-12  166.860001  147.759995  336.720001  56.610001  49.730000   

                   CAT      SP 500 Portfolio  Rank  
2011-11-14   72.899940  103.301254       0.0     0  
2011-11-15   73.307755  103.811737 -0.000027     1  
2011-11-16   72.310883  102.164955 -0.019917     2  
2011-11-17   70.845764  100.542900  -0.01363     3  
2011-11-18   70.936417  100.435875  0.003267     4  
...                ...         ...       ...   ...  
2021-11-08  214.250000  468.929993  0.004718  2512  
2021-11-09  209.809998  467.380005 -0.007728  2513  
2021-11-10  206.669998  463.619995  0.000029  2514  
2021-11-11  208.529999  463.769989  0.006381  2515  
2021-11-12  209.270004  467.269989 -0.000711  2516  

[2517 rows x 9 columns]

In [9]:
df['Sorted Portfolio']=df['Portfolio'].sort_values(ascending=True).values
df

JPM         WMT        MSFT         KO        PFE  \
2011-11-14   24.705299   46.650124   21.537199  24.791821  13.043631   
2011-11-15   24.819157   45.517323   21.683163  24.868612  13.096357   
2011-11-16   23.885593   44.899456   21.139864  24.506557  12.898625   
2011-11-17   23.141773   44.939053   20.710085  24.363930  12.832716   
2011-11-18   23.240440   45.335125   20.515478  24.645535  12.872263   
...                ...         ...         ...        ...        ...   
2021-11-08  169.059998  149.270004  336.989990  56.330002  48.330002   
2021-11-09  167.779999  149.789993  335.950012  56.490002  47.299999   
2021-11-10  167.619995  148.440002  330.799988  56.720001  49.020000   
2021-11-11  167.610001  148.500000  332.429993  56.740002  50.180000   
2021-11-12  166.860001  147.759995  336.720001  56.610001  49.730000   

                   CAT      SP 500 Portfolio  Rank Sorted Portfolio  
2011-11-14   72.899940  103.301254       0.0     0        -0.094578  
2011-11-15   73.307755  103.811737 -0.000027     1        -0.085876  
2011-11-16   72.310883  102.164955 -0.019917     2        -0.074026  
2011-11-17   70.845764  100.542900  -0.01363     3        -0.060748  
2011-11-18   70.936417  100.435875  0.003267     4        -0.051364  
...                ...         ...       ...   ...              ...  
2021-11-08  214.250000  468.929993  0.004718  2512         0.053897  
2021-11-09  209.809998  467.380005 -0.007728  2513         0.056094  
2021-11-10  206.669998  463.619995  0.000029  2514         0.068752  
2021-11-11  208.529999  463.769989  0.006381  2515         0.073542  
2021-11-12  209.270004  467.269989 -0.000711  2516         0.104212  

[2517 rows x 10 columns]

In [10]:
covariance=np.cov([i for i in df['Rank'].values],[i for i in df['Sorted Portfolio'].values])[0][1]
count=len(df)
Historical_average=df['Portfolio'].mean()
Expected_return=matrix.loc['Weights'].values.dot(matrix.loc['Returns,historical'].values.T)
GINI_Index=2*covariance/(Historical_average*count)
covariance,count,Historical_average,Expected_return,GINI_Index

(6.424130481030716,
 2517,
 0.0007057748682600625,
 0.16493718902327362,
 7.232608273484393)

In [11]:
#Notice In Economics we have seen that GINI Coefficient Lies betwwen 0 and 1,Because here we have negative return distribution we can have 1<
GINI_Index  =[]
weights=[]
for x in range(80000):
    p_weights=np.random.random(len(df.columns[:-4]))
    p_weights/=np.sum(p_weights)
    Portfolio=p_weights.dot(returns[df.columns[:-4]].T)
    Rank=[i for i in range(len(df))]
    Sorted_Portfolio=np.sort(Portfolio)
    covariance=np.cov(Rank,Sorted_Portfolio)[0][1]
    count=len(df)
    Historical_average=Portfolio.mean()
    Expected_return=p_weights.dot(matrix.loc['Returns,historical'].values.T)
    GINI_Index_1=2*covariance/(Historical_average*count)
    weights.append(p_weights)
    GINI_Index.append(GINI_Index_1)

p_wt = np.array(weights)
GINI_Index= np.array(GINI_Index)

    
p_wt,GINI_Index


(array([[0.05091594, 0.16339002, 0.21635562, 0.25211179, 0.18222601,
         0.13500061],
        [0.24357889, 0.28371276, 0.10707136, 0.28165766, 0.00144131,
         0.08253802],
        [0.1357123 , 0.01533284, 0.35945452, 0.09253803, 0.32972237,
         0.06723992],
        ...,
        [0.17327391, 0.05666213, 0.12522698, 0.26342188, 0.17547074,
         0.20594435],
        [0.2325437 , 0.23509806, 0.06590859, 0.17225074, 0.16980135,
         0.12439756],
        [0.23585168, 0.18343159, 0.21785657, 0.05468378, 0.08934993,
         0.21882644]]),
 array([7.10158899, 7.56406607, 6.56948416, ..., 7.87699029, 7.59548915,
        7.24801303]))

In [12]:
p_wt[GINI_Index.argmin()]

array([0.15653752, 0.13826121, 0.47700644, 0.01666183, 0.20618128,
       0.00535173])

In [13]:
GINI_Index[GINI_Index.argmin()]

6.1480136161240235