In [1]:
import random
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import math
import scipy.stats as stats
from scipy.stats import norm
from scipy.stats import kurtosis
import requests
%matplotlib inline

In [2]:
df=pd.read_excel('C:\\Users\\nafissaad\\Downloads\\NEDL_Portfolio_Higher_Moments.xlsx',index_col='Date')
df=df[0:1259][['Apple','Tesla','Walmart','Caterpillar','Coca-Cola']]
df.to_excel('C:\\Users\\nafissaad\\Downloads\\NEDL_Portfolio_Higher_Moments.xlsx')
returns=df.pct_change()
returns

Apple     Tesla   Walmart  Caterpillar  Coca-Cola
Date                                                            
2015-04-23       NaN       NaN       NaN          NaN        NaN
2015-04-24  0.004704 -0.000778  0.008335    -0.002241  -0.001465
2015-04-27  0.018192  0.060065 -0.005887     0.008629  -0.001467
2015-04-28 -0.015756 -0.004621 -0.003402     0.010196  -0.001470
2015-04-29 -0.014706  0.008547 -0.015424     0.015081  -0.006868
...              ...       ...       ...          ...        ...
2020-04-16  0.007946  0.021073  0.027726     0.015153  -0.010712
2020-04-17 -0.013569  0.011648 -0.001587     0.027204   0.020382
2020-04-20 -0.020757 -0.009988 -0.017181    -0.014617  -0.031835
2020-04-21 -0.030910 -0.079908 -0.004929    -0.041449  -0.024715
2020-04-22  0.028804  0.066097  0.018420     0.007192   0.006611

[1259 rows x 5 columns]

In [3]:
mean=returns.mean()
mean

Apple          0.000765
Tesla          0.001506
Walmart        0.000502
Caterpillar    0.000392
Coca-Cola      0.000157
dtype: float64

In [4]:
standard_deviation=returns.std()
standard_deviation

Apple          0.018111
Tesla          0.033068
Walmart        0.014087
Caterpillar    0.018943
Coca-Cola      0.011779
dtype: float64

In [5]:
Skewnesses=returns.skew()
Skewnesses

Apple         -0.136472
Tesla          0.268462
Walmart        0.723344
Caterpillar   -0.416776
Coca-Cola     -1.039594
dtype: float64

In [6]:
kurtosises=kurtosis(returns.dropna())
kurtosises

array([ 7.77444385,  6.88362246, 17.76876112,  5.62947626, 13.46745244])

In [7]:
theta=np.ones(6)*5
theta

array([5., 5., 5., 5., 5., 5.])

In [8]:
weights_1=np.ones(5)*0.2
weights_1.sum()

1.0

In [9]:
returns[returns.columns[:-1]]

Apple     Tesla   Walmart  Caterpillar
Date                                                 
2015-04-23       NaN       NaN       NaN          NaN
2015-04-24  0.004704 -0.000778  0.008335    -0.002241
2015-04-27  0.018192  0.060065 -0.005887     0.008629
2015-04-28 -0.015756 -0.004621 -0.003402     0.010196
2015-04-29 -0.014706  0.008547 -0.015424     0.015081
...              ...       ...       ...          ...
2020-04-16  0.007946  0.021073  0.027726     0.015153
2020-04-17 -0.013569  0.011648 -0.001587     0.027204
2020-04-20 -0.020757 -0.009988 -0.017181    -0.014617
2020-04-21 -0.030910 -0.079908 -0.004929    -0.041449
2020-04-22  0.028804  0.066097  0.018420     0.007192

[1259 rows x 4 columns]

In [10]:
returns['Portfolio 1']=returns.dot(weights_1)
returns

Apple     Tesla   Walmart  Caterpillar  Coca-Cola  Portfolio 1
Date                                                                         
2015-04-23       NaN       NaN       NaN          NaN        NaN          NaN
2015-04-24  0.004704 -0.000778  0.008335    -0.002241  -0.001465     0.001711
2015-04-27  0.018192  0.060065 -0.005887     0.008629  -0.001467     0.015906
2015-04-28 -0.015756 -0.004621 -0.003402     0.010196  -0.001470    -0.003011
2015-04-29 -0.014706  0.008547 -0.015424     0.015081  -0.006868    -0.002674
...              ...       ...       ...          ...        ...          ...
2020-04-16  0.007946  0.021073  0.027726     0.015153  -0.010712     0.012237
2020-04-17 -0.013569  0.011648 -0.001587     0.027204   0.020382     0.008816
2020-04-20 -0.020757 -0.009988 -0.017181    -0.014617  -0.031835    -0.018876
2020-04-21 -0.030910 -0.079908 -0.004929    -0.041449  -0.024715    -0.036382
2020-04-22  0.028804  0.066097  0.018420     0.007192   0.006611     0.025424

[1259 rows x 6 columns]

In [11]:
mean=returns.mean()
standard_deviation=returns.std()
Skewnesses=returns.skew()
kurtosises=kurtosis(returns.dropna())
standard_deviation

Apple          0.018111
Tesla          0.033068
Walmart        0.014087
Caterpillar    0.018943
Coca-Cola      0.011779
Portfolio 1    0.013246
dtype: float64

In [12]:
#our expected return is stocastic, it cant be measured based on past data. so it can be possible future gainers are 
#from past losers.so we will chose our bet on risk. we want to bet on possitive skewness and avoid negative skewness
mean_Annualized=(1+mean)**252-1
mean_Annualized

Apple          0.212601
Tesla          0.461262
Walmart        0.134957
Caterpillar    0.103801
Coca-Cola      0.040315
Portfolio 1    0.182246
dtype: float64

In [13]:
Standard_deviation_Annualized=standard_deviation*np.sqrt(252)
Standard_deviation_Annualized

Apple          0.287498
Tesla          0.524937
Walmart        0.223624
Caterpillar    0.300717
Coca-Cola      0.186993
Portfolio 1    0.210274
dtype: float64

In [14]:
utility_1=mean_Annualized-theta*Standard_deviation_Annualized**2/2
utility_1

Apple          0.005963
Tesla         -0.227636
Walmart        0.009938
Caterpillar   -0.122276
Coca-Cola     -0.047101
Portfolio 1    0.071708
dtype: float64

In [15]:
utility_2=mean_Annualized-theta*Standard_deviation_Annualized**2/2+theta**2*Standard_deviation_Annualized**3*Skewnesses/6-theta**3*Standard_deviation_Annualized**4*kurtosises/720
utility_2

Apple         -0.016770
Tesla         -0.156575
Walmart        0.035928
Caterpillar   -0.177493
Coca-Cola     -0.078282
Portfolio 1    0.047001
dtype: float64

In [16]:
#when we take skewness and kurtosis into out calculation tesla is more preferable than Caterpillar because Tesla has positive tail


In [17]:
Utility  =[]
weights=[]

for x in range(80000):
    p_weights=np.random.random(len(returns.columns[:-1]))
    p_weights/=np.sum(p_weights)
    ret=returns[returns.columns[:-1]].dot(p_weights)
    
    mean_Annualized=(1+ret.mean())**252-1
    theta=5
    Skewnesses=ret.skew()
    kurtosises=kurtosis(ret.dropna())
    
    Standard_deviation_Annualized=ret.std()*np.sqrt(252)
    utility_2=mean_Annualized-theta*Standard_deviation_Annualized**2/2+theta**2*Standard_deviation_Annualized**3*Skewnesses/6-theta**3*Standard_deviation_Annualized**4*kurtosises/720

    weights.append(p_weights)
    Utility.append(utility_2)

p_wt = np.array(weights)
util= np.array(Utility)

    
p_wt,util

(array([[0.04944153, 0.41391653, 0.1692324 , 0.25418501, 0.11322453],
        [0.08080098, 0.27344927, 0.08270712, 0.31281377, 0.25022886],
        [0.07077475, 0.19787913, 0.18418282, 0.48104762, 0.06611567],
        ...,
        [0.13815765, 0.11226459, 0.34276532, 0.39760555, 0.00920689],
        [0.26587214, 0.14993568, 0.37505678, 0.01545172, 0.19368367],
        [0.24717494, 0.29664746, 0.1803739 , 0.23260619, 0.04319751]]),
 array([0.02669059, 0.01673098, 0.01335327, ..., 0.03971898, 0.06839789,
        0.04688943]))

In [18]:
util.argmax()

8907

In [19]:
util[util.argmax()]

0.08632240790523911

In [20]:
p_wt[util.argmax()]

array([0.18241196, 0.26104175, 0.52924722, 0.01613635, 0.01116272])

In [ ]:
#Utility=theta(risk aversion 0 to 5)*standard_deviation^2/2#The higher theta is more risk averse