In [1]:
import random
import numpy as np
import yfinance as yf
import pandas as pd
from matplotlib import pyplot as plt
from scipy.stats import norm
import math
import scipy.stats as stats
from scipy.stats import norm
from datetime import datetime, timedelta
import statsmodels.api as sm
import requests
%matplotlib inline

In [2]:
tickers=['Large stocks','Small stocks','Treasury bonds','Corporate bonds','Gold','REIT']

In [3]:
df=df=pd.read_excel('C:\\Users\\nafissaad\\Downloads\\NEDL_Diversification_Ratio.xlsx',index_col='Date')
df

Large stocks  Small stocks  Treasury bonds  Corporate bonds  \
Date                                                                      
2016-03-30    187.404327    103.284630      115.934731        63.101669   
2016-03-31    186.949509    103.563309      116.757210        63.186726   
2016-04-01    188.222961    103.804810      117.061729        63.232586   
2016-04-04    187.613495    103.024544      117.133392        63.077179   
2016-04-05    185.739670    101.835556      118.414383        62.844059   
...                  ...           ...             ...              ...   
2021-03-23    389.500000    209.498306      137.490005        86.459999   
2021-03-24    387.519989    206.307007      138.229996        86.510002   
2021-03-25    389.700012    210.350006      137.139999        86.660004   
2021-03-26    395.980011    214.119995      136.660004        86.919998   
2021-03-29    395.779999    209.979996      135.500000        86.970001   

                  Gold       REIT  
Date                               
2016-03-30  117.099998  67.771255  
2016-03-31  117.639999  68.186249  
2016-04-01  116.930000  68.096741  
2016-04-04  116.150002  67.999100  
2016-04-05  117.660004  67.551575  
...                ...        ...  
2021-03-23  161.809998  90.471031  
2021-03-24  162.369995  89.963997  
2021-03-25  161.779999  90.879997  
2021-03-26  162.240005  92.839996  
2021-03-29  160.309998  92.300003  

[1259 rows x 6 columns]

In [4]:
df=df.pct_change().dropna()
df

Large stocks  Small stocks  Treasury bonds  Corporate bonds  \
Date                                                                      
2016-03-31     -0.002427      0.002698        0.007094         0.001348   
2016-04-01      0.006812      0.002332        0.002608         0.000726   
2016-04-04     -0.003238     -0.007517        0.000612        -0.002458   
2016-04-05     -0.009988     -0.011541        0.010936        -0.003696   
2016-04-06      0.010921      0.011220       -0.007262         0.008408   
...                  ...           ...             ...              ...   
2021-03-23     -0.007871     -0.028578        0.009027         0.001042   
2021-03-24     -0.005083     -0.015233        0.005382         0.000578   
2021-03-25      0.005626      0.019597       -0.007885         0.001734   
2021-03-26      0.016115      0.017922       -0.003500         0.003000   
2021-03-29     -0.000505     -0.019335       -0.008488         0.000575   

                Gold      REIT  
Date                            
2016-03-31  0.004611  0.006123  
2016-04-01 -0.006035 -0.001313  
2016-04-04 -0.006671 -0.001434  
2016-04-05  0.013000 -0.006581  
2016-04-06 -0.006119  0.002409  
...              ...       ...  
2021-03-23 -0.007301 -0.001427  
2021-03-24  0.003461 -0.005604  
2021-03-25 -0.003634  0.010182  
2021-03-26  0.002843  0.021567  
2021-03-29 -0.011896 -0.005816  

[1258 rows x 6 columns]

In [5]:
metrix=pd.DataFrame(columns=[tickers[:-1]],index=['Standerd deviation','Weights','Sum weights'])
metrix

Large stocks Small stocks Treasury bonds Corporate bonds  \
Standerd deviation          NaN          NaN            NaN             NaN   
Weights                     NaN          NaN            NaN             NaN   
Sum weights                 NaN          NaN            NaN             NaN   

                   Gold  
Standerd deviation  NaN  
Weights             NaN  
Sum weights         NaN

In [6]:
cov=df.cov()*252
cov

Large stocks  Small stocks  Treasury bonds  Corporate bonds  \
Large stocks         0.035152      0.038029       -0.010105         0.013492   
Small stocks         0.038029      0.048442       -0.011319         0.015676   
Treasury bonds      -0.010105     -0.011319        0.019336        -0.003121   
Corporate bonds      0.013492      0.015676       -0.003121         0.008171   
Gold                 0.000386      0.000031        0.006231         0.001158   
REIT                 0.031819      0.038443       -0.005676         0.014779   

                     Gold      REIT  
Large stocks     0.000386  0.031819  
Small stocks     0.000031  0.038443  
Treasury bonds   0.006231 -0.005676  
Corporate bonds  0.001158  0.014779  
Gold             0.018822  0.002938  
REIT             0.002938  0.050357

In [7]:
tickers

['Large stocks',
 'Small stocks',
 'Treasury bonds',
 'Corporate bonds',
 'Gold',
 'REIT']

In [8]:
Asset_class_weights=pd.DataFrame(columns=[['volatility','varinace','Large stocks','Small stocks','Treasury bonds','Corporate bonds','Gold','REIT']],index=['Equal-weighted','Risk parity'])
Asset_class_weights

volatility varinace Large stocks Small stocks Treasury bonds  \
Equal-weighted        NaN      NaN          NaN          NaN            NaN   
Risk parity           NaN      NaN          NaN          NaN            NaN   

               Corporate bonds Gold REIT  
Equal-weighted             NaN  NaN  NaN  
Risk parity                NaN  NaN  NaN

In [9]:
Asset_class_weights.loc['Equal-weighted',tickers]=1/6
Asset_class_weights.loc['Equal-weighted','volatility']=(Asset_class_weights.loc['Equal-weighted',tickers].values.T.dot((df.cov()*252).dot(Asset_class_weights.loc['Equal-weighted',tickers].values)))**(1/2)
Asset_class_weights.loc['Equal-weighted','varinace']=(Asset_class_weights.loc['Equal-weighted',tickers].values.T.dot((df.cov()*252).dot(Asset_class_weights.loc['Equal-weighted',tickers].values)))

In [10]:
Asset_class_weights

volatility  varinace Large stocks Small stocks Treasury bonds  \
Equal-weighted   0.111281  0.012384     0.166667     0.166667       0.166667   
Risk parity           NaN       NaN          NaN          NaN            NaN   

               Corporate bonds      Gold      REIT  
Equal-weighted        0.166667  0.166667  0.166667  
Risk parity                NaN       NaN       NaN

In [11]:
risk_contributer=pd.DataFrame(columns=[['volatility','varinace','Large stocks','Small stocks','Treasury bonds','Corporate bonds','Gold','REIT']],index=['Equal-weighted','Risk parity'])
risk_contributer

volatility varinace Large stocks Small stocks Treasury bonds  \
Equal-weighted        NaN      NaN          NaN          NaN            NaN   
Risk parity           NaN      NaN          NaN          NaN            NaN   

               Corporate bonds Gold REIT  
Equal-weighted             NaN  NaN  NaN  
Risk parity                NaN  NaN  NaN

In [12]:
risk_contributer.loc['Equal-weighted',tickers]=((df.cov()*252).values.dot(Asset_class_weights.loc['Equal-weighted',tickers].values)*Asset_class_weights.loc['Equal-weighted',tickers].values)/Asset_class_weights.loc['Equal-weighted','varinace'].values
risk_contributer#((covarinace*weights)*weights)/variance

volatility varinace Large stocks Small stocks Treasury bonds  \
Equal-weighted        NaN      NaN     0.243993     0.290044      -0.010438   
Risk parity           NaN      NaN          NaN          NaN            NaN   

               Corporate bonds      Gold      REIT  
Equal-weighted        0.112504  0.066322  0.297575  
Risk parity                NaN       NaN       NaN

In [13]:
risk_contributer.loc['Risk parity',tickers]=1/6
risk_contributer

volatility varinace Large stocks Small stocks Treasury bonds  \
Equal-weighted        NaN      NaN     0.243993     0.290044      -0.010438   
Risk parity           NaN      NaN     0.166667     0.166667       0.166667   

               Corporate bonds      Gold      REIT  
Equal-weighted        0.112504  0.066322  0.297575  
Risk parity           0.166667  0.166667  0.166667

In [14]:
deviation=abs(risk_contributer.loc['Equal-weighted',tickers].values-[1/6 for i in range(6)])
deviation

array([0.07732607073601785, 0.12337739936418216, 0.17710503360085506,
       0.054162498731154016, 0.10034458897314509, 0.13090865120495424],
      dtype=object)

In [15]:
deviation.sum()# we have to minimize the deviation

0.6632242426103084

In [16]:
deviation  =[]
weights=[]
for x in range(80000):
    p_weights=np.random.random(len(tickers))
    p_weights/=np.sum(p_weights)
    variance=(p_weights.T.dot(cov.dot(p_weights)))
    equal_weighted_risk=(cov.values.dot(p_weights)*p_weights)/variance
    deviation_1=sum(abs(equal_weighted_risk-np.array([1/6 for i in range(6)])))
    weights.append(p_weights)
    deviation.append(deviation_1)

p_wt = np.array(weights)
deviation= np.array(deviation)

    
p_wt,deviation

(array([[0.06057366, 0.22537662, 0.20112066, 0.08476318, 0.22408661,
         0.20407928],
        [0.31312768, 0.28221452, 0.00106794, 0.04664403, 0.20718035,
         0.14976547],
        [0.05272717, 0.13520144, 0.05182381, 0.25700448, 0.22720706,
         0.27603605],
        ...,
        [0.11071653, 0.08911606, 0.13791325, 0.17116001, 0.29131829,
         0.19977586],
        [0.06887073, 0.07177987, 0.35471807, 0.00278074, 0.11456261,
         0.38728797],
        [0.19429803, 0.03089777, 0.11001094, 0.23934582, 0.18882354,
         0.2366239 ]]),
 array([0.80975311, 0.87496574, 0.70722585, ..., 0.47821607, 1.02180408,
        0.76210688]))

In [17]:
np.argmin(deviation)

53521

In [18]:
deviation[np.argmin(deviation)]

0.08563113075825218

In [19]:
p_wt[np.argmin(deviation)]

array([0.09960244, 0.09334528, 0.28481594, 0.22805107, 0.20164339,
       0.09254188])

In [20]:
variance=(p_wt[np.argmin(deviation)].T.dot((cov).dot(p_wt[np.argmin(deviation)])))
weighted_risk=(cov.values.dot(p_wt[np.argmin(deviation)])*p_wt[np.argmin(deviation)])/variance
deviation_1=sum(abs(weighted_risk-np.array([1/6 for i in range(6)])))
deviation_1

0.08563113075825218

In [21]:
(p_wt[np.argmin(deviation)].T.dot(cov).dot(p_wt[np.argmin(deviation)]))**(1/2)

0.08301615763777771

In [22]:
weighted_risk

array([0.14846211, 0.16558127, 0.14314105, 0.17812045, 0.17986818,
       0.18482693])