In [311]:
#'https://www.investing.com/equities/adn-telecom-ltd-balance-sheet'
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

In [312]:
re.sub(" ", " ",'  i am        nafis ').strip().replace('  ',' ')

'i am    nafis'

In [313]:
re.sub(" +", " ",'  i am        nafis ').strip().replace('  ',' ')

'i am nafis'

In [314]:
folder='Fortune Shoes Ltd.'
Income_Statement=pd.read_excel('C:\\Users\\nafissaad\\Tutorial\\Fundamental analysis\\My Portfolio\\'+folder+'\\BooK.xlsx',sheet_name='Income_Statement',index_col=0)
Balance_Sheet=pd.read_excel('C:\\Users\\nafissaad\\Tutorial\\Fundamental analysis\\My Portfolio\\'+folder+'\\BooK.xlsx',sheet_name='Balance_Sheet',index_col=0)
Balance_Sheet

2022       2021  \
Assets                                                                     
Fiscal year is July-June. All values BDT Millions.  2022.0000  2021.0000   
Cash & Short Term Investments                        242.0000   134.0000   
Cash Only                                             16.0000    32.0000   
Cash & Short Term Investments Growth                   0.8056     3.8285   
Cash & ST Investments / Total Assets                   0.0853     0.0513   
...                                                       ...        ...   
Common Equity / Total Assets                           0.8194     0.8445   
Total Shareholders' Equity                          2324.0000  2204.0000   
Total Shareholders' Equity / Total Assets              0.8194     0.8445   
Total Equity                                        2324.0000  2204.0000   
Liabilities & Shareholders' Equity                  2837.0000  2609.0000   

                                                         2020       2019  \
Assets                                                                     
Fiscal year is July-June. All values BDT Millions.  2020.0000  2019.0000   
Cash & Short Term Investments                         28.0000    32.0000   
Cash Only                                             28.0000    32.0000   
Cash & Short Term Investments Growth                  -0.1248     2.9290   
Cash & ST Investments / Total Assets                   0.0121     0.0152   
...                                                       ...        ...   
Common Equity / Total Assets                           0.8768     0.9125   
Total Shareholders' Equity                          2009.0000  1909.0000   
Total Shareholders' Equity / Total Assets              0.8768     0.9125   
Total Equity                                        2009.0000  1909.0000   
Liabilities & Shareholders' Equity                  2291.0000  2092.0000   

                                                         2018  5-year trend  
Assets                                                                       
Fiscal year is July-June. All values BDT Millions.  2018.0000  5-year trend  
Cash & Short Term Investments                          8.0000           NaN  
Cash Only                                              8.0000           NaN  
Cash & Short Term Investments Growth                      NaN           NaN  
Cash & ST Investments / Total Assets                   0.0044           NaN  
...                                                       ...           ...  
Common Equity / Total Assets                           0.9118           NaN  
Total Shareholders' Equity                          1690.0000           NaN  
Total Shareholders' Equity / Total Assets              0.9118           NaN  
Total Equity                                        1690.0000           NaN  
Liabilities & Shareholders' Equity                  1854.0000           NaN  

[69 rows x 6 columns]

In [315]:
Balance_Sheet.columns=Income_Statement.columns
#Balance_Sheet.drop_duplicates(inplace=True)
Balance_Sheet.dropna(how='all',axis=0,inplace=True)
Balance_Sheet=Balance_Sheet.replace('-','')
Balance_Sheet

2022       2021  \
Assets                                                                     
Fiscal year is July-June. All values BDT Millions.  2022.0000  2021.0000   
Cash & Short Term Investments                        242.0000   134.0000   
Cash Only                                             16.0000    32.0000   
Cash & Short Term Investments Growth                   0.8056     3.8285   
Cash & ST Investments / Total Assets                   0.0853     0.0513   
...                                                       ...        ...   
Common Equity / Total Assets                           0.8194     0.8445   
Total Shareholders' Equity                          2324.0000  2204.0000   
Total Shareholders' Equity / Total Assets              0.8194     0.8445   
Total Equity                                        2324.0000  2204.0000   
Liabilities & Shareholders' Equity                  2837.0000  2609.0000   

                                                         2020       2019  \
Assets                                                                     
Fiscal year is July-June. All values BDT Millions.  2020.0000  2019.0000   
Cash & Short Term Investments                         28.0000    32.0000   
Cash Only                                             28.0000    32.0000   
Cash & Short Term Investments Growth                  -0.1248     2.9290   
Cash & ST Investments / Total Assets                   0.0121     0.0152   
...                                                       ...        ...   
Common Equity / Total Assets                           0.8768     0.9125   
Total Shareholders' Equity                          2009.0000  1909.0000   
Total Shareholders' Equity / Total Assets              0.8768     0.9125   
Total Equity                                        2009.0000  1909.0000   
Liabilities & Shareholders' Equity                  2291.0000  2092.0000   

                                                         2018  5-year trend  
Assets                                                                       
Fiscal year is July-June. All values BDT Millions.  2018.0000  5-year trend  
Cash & Short Term Investments                          8.0000           NaN  
Cash Only                                              8.0000           NaN  
Cash & Short Term Investments Growth                      NaN           NaN  
Cash & ST Investments / Total Assets                   0.0044           NaN  
...                                                       ...           ...  
Common Equity / Total Assets                           0.9118           NaN  
Total Shareholders' Equity                          1690.0000           NaN  
Total Shareholders' Equity / Total Assets              0.9118           NaN  
Total Equity                                        1690.0000           NaN  
Liabilities & Shareholders' Equity                  1854.0000           NaN  

[69 rows x 6 columns]

In [316]:
Income_Statement.dropna(how='all',axis=0,inplace=True)
Income_Statement=Income_Statement.replace('-','')

In [317]:
with pd.ExcelWriter('C:\\Users\\nafissaad\\Tutorial\\Fundamental analysis\\My Portfolio\\'+folder+'\\BooK.xlsx') as writer:
    Balance_Sheet.to_excel(writer, sheet_name='Balance_Sheet')
    Income_Statement.to_excel(writer, sheet_name='Income_Statement')


In [318]:
x=pd.read_excel("C:\\Users\\nafissaad\\Tutorial\\Fundamental analysis\\My Portfolio\\Port_folio_draft.xlsx", index_col='Unnamed: 0')
x

Full Name  \
ISLAMIBANK                     Islami Bank Bangladesh Limited   
RAKCERAMIC                  RAK Ceramics (Bangladesh) Limited   
SALAMCRST                     S. Alam Cold Rolled Steels Ltd.   
POWERGRID               Power Grid Company of Bangladesh Ltd.   
BATBC       British American Tobacco Bangladesh Company Li...   
RENATA                                            Renata Ltd.   
MARICO                              Marico Bangladesh Limited   
SINGERBD                                Singer Bangladesh Ltd   
LINDEBD                                  Linde Bangladesh Ltd   
SUMITPOWER                                   Summit Power Ltd   
BERGERPBL                             Berger Paints India Ltd   
BXPHARMA                          Beximco Pharmaceuticals Ltd   
SQURPHARMA                         Square Pharmaceuticals Ltd   
SAPORTL                              Summit Alliance Port Ltd   
BSCCL                         Bangladesh Submarine Cables PLC   
GP                                           Grameenphone Ltd   
SQUARETEXT                                 Square Textile Ltd   
 EXIMBANK                Export Import Bank of Bangladesh Ltd   
HEIDELBCEM                   Heidelberg Cement Bangladesh Ltd   
 OLYMPIC                       Olympic Industries Ltd OLYMPIC   
BSRMSTEEL                                     BSRM Steels Ltd   
BEXIMCO                                           BEXIMCO Ltd   
NATLIFEINS                     National Life Insurance Co Ltd   
HFL                                         Hamid Fabrics Ltd   
BATASHOE                        Bata Shoe Co (Bangladesh) Ltd   
 APEXSPINN                 Apex Spinning & Knitting Mills Ltd   
UPGDCL         United Power Generation & Distribution Co. Ltd   
DELTALIFE                      Green Delta Insurance Co. Ltd.   
CROWNCEMNT                                   Crown Cement PLC   
BENGALWTL                  Bengal Windsor Thermoplastics Ltd.   
EHL                                      Eastern Housing Ltd.   
IBNSINA                  IBN SINA Pharmaceutical Industry PLC   
WALTONHIL                      Walton Hi-Tech Industries Ltd.   
UNIQUEHRL                         Unique Hotel & Resorts Ltd.   
UNILEVERCL                        Unilever Consumer Care Ltd.   
KDSALTD                                  KDS Accessories Ltd.   
JHRML               JMI Hospital Requisite Manufacturing Ltd.   
ANDTEL                                 Adn Telecom Ltd (ADNT)   
ITC                                       IT Consultants Ltd.   
SIMTEX                                 Simtex Industries Ltd.   
APEXFOOT                                   Apex Footwear Ltd.   
APEXFOODS                                     Apex Foods Ltd.   

                                 Sector Evaluation  
ISLAMIBANK                         Bank          M  
RAKCERAMIC                      Ceramic          M  
SALAMCRST                   Engineering          P  
POWERGRID                  Fuel & Power          P  
BATBC                     FOOD & Allied          G  
RENATA                    FOOD & Allied          G  
MARICO      Pharmaceuticals & Chemicals          M  
SINGERBD                    Engineering          P  
LINDEBD                     Engineering          G  
SUMITPOWER                 Fuel & Power          M  
BERGERPBL                 Miscellaneous          G  
BXPHARMA    Pharmaceuticals & Chemicals          G  
SQURPHARMA  Pharmaceuticals & Chemicals          G  
SAPORTL          Services & Real Estate          M  
BSCCL                 Telecommunication          G  
GP                    Telecommunication          M  
SQUARETEXT                      Textile          M  
 EXIMBANK                          Bank          M  
HEIDELBCEM                       Cement          p  
 OLYMPIC                  FOOD & Allied          G  
BSRMSTEEL                  Iron & Steel          P  
BEXIMCO                   Miscellaneous          M  
NATLIFEINS                    Insuran

In [319]:
folder

'Fortune Shoes Ltd.'

In [320]:
ticker=re.sub(" +", " ",'FORTUNE')
Analysis=pd.DataFrame(columns=['Full Name','Sector','Evaluation'],index=[ticker])
Analysis.loc[ticker,'Full Name']=folder
Analysis.loc[ticker,'Sector']='Tannery Industries'
Analysis.loc[ticker,'Evaluation']='G'
Analysis=pd.concat([x,Analysis],axis=0)
Analysis=Analysis.drop_duplicates()#Drop Duplicate
Analysis

Full Name  \
ISLAMIBANK                     Islami Bank Bangladesh Limited   
RAKCERAMIC                  RAK Ceramics (Bangladesh) Limited   
SALAMCRST                     S. Alam Cold Rolled Steels Ltd.   
POWERGRID               Power Grid Company of Bangladesh Ltd.   
BATBC       British American Tobacco Bangladesh Company Li...   
RENATA                                            Renata Ltd.   
MARICO                              Marico Bangladesh Limited   
SINGERBD                                Singer Bangladesh Ltd   
LINDEBD                                  Linde Bangladesh Ltd   
SUMITPOWER                                   Summit Power Ltd   
BERGERPBL                             Berger Paints India Ltd   
BXPHARMA                          Beximco Pharmaceuticals Ltd   
SQURPHARMA                         Square Pharmaceuticals Ltd   
SAPORTL                              Summit Alliance Port Ltd   
BSCCL                         Bangladesh Submarine Cables PLC   
GP                                           Grameenphone Ltd   
SQUARETEXT                                 Square Textile Ltd   
 EXIMBANK                Export Import Bank of Bangladesh Ltd   
HEIDELBCEM                   Heidelberg Cement Bangladesh Ltd   
 OLYMPIC                       Olympic Industries Ltd OLYMPIC   
BSRMSTEEL                                     BSRM Steels Ltd   
BEXIMCO                                           BEXIMCO Ltd   
NATLIFEINS                     National Life Insurance Co Ltd   
HFL                                         Hamid Fabrics Ltd   
BATASHOE                        Bata Shoe Co (Bangladesh) Ltd   
 APEXSPINN                 Apex Spinning & Knitting Mills Ltd   
UPGDCL         United Power Generation & Distribution Co. Ltd   
DELTALIFE                      Green Delta Insurance Co. Ltd.   
CROWNCEMNT                                   Crown Cement PLC   
BENGALWTL                  Bengal Windsor Thermoplastics Ltd.   
EHL                                      Eastern Housing Ltd.   
IBNSINA                  IBN SINA Pharmaceutical Industry PLC   
WALTONHIL                      Walton Hi-Tech Industries Ltd.   
UNIQUEHRL                         Unique Hotel & Resorts Ltd.   
UNILEVERCL                        Unilever Consumer Care Ltd.   
KDSALTD                                  KDS Accessories Ltd.   
JHRML               JMI Hospital Requisite Manufacturing Ltd.   
ANDTEL                                 Adn Telecom Ltd (ADNT)   
ITC                                       IT Consultants Ltd.   
SIMTEX                                 Simtex Industries Ltd.   
APEXFOOT                                   Apex Footwear Ltd.   
APEXFOODS                                     Apex Foods Ltd.   
FORTUNE                                    Fortune Shoes Ltd.   

                                 Sector Evaluation  
ISLAMIBANK                         Bank          M  
RAKCERAMIC                      Ceramic          M  
SALAMCRST                   Engineering          P  
POWERGRID                  Fuel & Power          P  
BATBC                     FOOD & Allied          G  
RENATA                    FOOD & Allied          G  
MARICO      Pharmaceuticals & Chemicals          M  
SINGERBD                    Engineering          P  
LINDEBD                     Engineering          G  
SUMITPOWER                 Fuel & Power          M  
BERGERPBL                 Miscellaneous          G  
BXPHARMA    Pharmaceuticals & Chemicals          G  
SQURPHARMA  Pharmaceuticals & Chemicals          G  
SAPORTL          Services & Real Estate          M  
BSCCL                 Telecommunication          G  
GP                    Telecommunication          M  
SQUARETEXT                      Textile          M  
 EXIMBANK                          Bank          M  
HEIDELBCEM                       Cement          p  
 OLYMPIC                  FOOD & Allied          G  
BSRMSTEEL                  Iron & Steel          P  
BEXIMCO                  

In [321]:
Analysis.loc[ticker,'Full Name']

'Fortune Shoes Ltd.'

In [322]:
folder=Analysis.loc[ticker,'Full Name']
path = "C:\\Users\\nafissaad\\Tutorial\\Fundamental analysis\\My Portfolio\\"+folder+"\\"
Balance_Sheet=pd.read_excel(path+'Book.xlsx',sheet_name='Balance_Sheet',index_col=0)
Income_Satetment=pd.read_excel(path+'BooK.xlsx',sheet_name='Income_Statement',index_col=0)
Income_Satetment

2022       2021  \
Fiscal year is July-June. All values BDT Millions.                         
Sales/Revenue                                       1705.0000  1404.0000   
Sales Growth                                           0.2140     0.1796   
Cost of Goods Sold (COGS) incl. D&A                 1407.0000  1087.0000   
COGS excluding D&A                                  1337.0000  1024.0000   
Depreciation & Amortization Expense                   70.0000    63.0000   
Depreciation                                          70.0000    63.0000   
COGS Growth                                            0.2949     0.0894   
Gross Income                                         298.0000   317.0000   
Gross Income Growth                                   -0.0629     0.6460   
Gross Profit Margin                                    0.1745        NaN   
SG&A Expense                                          64.0000    49.0000   
Other SG&A                                            64.0000    49.0000   
SGA Growth                                             0.2969    -0.1143   
EBIT                                                 234.0000        NaN   
Non Operating Income/Expense                         245.0000    26.0000   
Non-Operating Interest Income                          0.0000        NaN   
Interest Expense                                      45.0000     8.0000   
Interest Expense Growth                                4.3729     0.6781   
Gross Interest Expense                                45.0000     8.0000   
Pretax Income                                        433.0000   286.0000   
Pretax Income Growth                                   0.5146     1.1340   
Pretax Margin                                          0.2539        NaN   
Income Tax                                            59.0000    40.0000   
Income Tax - Current Domestic                         48.0000    27.0000   
Income Tax - Deferred Domestic                        11.0000    13.0000   
Consolidated Net Income                              374.0000   245.0000   
Net Income                                           374.0000   245.0000   
Net Income Growth                                      0.5239     1.0943   
Net Margin                                             0.2194        NaN   
Net Income After Extraordinaries                     374.0000   245.0000   
Net Income Available to Common                       374.0000   245.0000   
EPS (Basic)                                            2.1900     1.4400   
EPS (Basic) Growth                                     0.5239     1.0944   
Basic Shares Outstanding                             171.0000   171.0000   
EPS (Diluted)                                          2.1900     1.4400   
EPS (Diluted) Growth                                   0.5239     1.0943   
Diluted Shares Outstanding                           171.0000   171.0000   
EBITDA                                               304.0000   331.0000   
EBITDA Growth                                         -0.0809     0.7084   
EBITDA Margin                                          0.1783        NaN   
EBIT                                                 234.0000        NaN   

                                                         2020       2019  \
Fiscal year is July-June. All values BDT Millions.                         
Sales/Revenue                                       1191.0000  1541.0000   
Sales Growth                                          -0.2273     0.1178   
Cost of Goods Sold (COGS) incl. D&A                  998.0000  1241.0000   
COGS excluding D&A                                   941.0000  1182.0000   
Depreciation & Amortization Expense                   56.0000    59.0000   
Depreciation                                          56.0000    59.0000   
COGS Growth                                           -0.1958     0.1208   
Gross Income                                         193.0000   300.0000   
Gross Income Growth         

In [323]:
Balance_Sheet

2022       2021  \
Assets                                                                     
Fiscal year is July-June. All values BDT Millions.  2022.0000  2021.0000   
Cash & Short Term Investments                        242.0000   134.0000   
Cash Only                                             16.0000    32.0000   
Cash & Short Term Investments Growth                   0.8056     3.8285   
Cash & ST Investments / Total Assets                   0.0853     0.0513   
...                                                       ...        ...   
Common Equity / Total Assets                           0.8194     0.8445   
Total Shareholders' Equity                          2324.0000  2204.0000   
Total Shareholders' Equity / Total Assets              0.8194     0.8445   
Total Equity                                        2324.0000  2204.0000   
Liabilities & Shareholders' Equity                  2837.0000  2609.0000   

                                                         2020       2019  \
Assets                                                                     
Fiscal year is July-June. All values BDT Millions.  2020.0000  2019.0000   
Cash & Short Term Investments                         28.0000    32.0000   
Cash Only                                             28.0000    32.0000   
Cash & Short Term Investments Growth                  -0.1248     2.9290   
Cash & ST Investments / Total Assets                   0.0121     0.0152   
...                                                       ...        ...   
Common Equity / Total Assets                           0.8768     0.9125   
Total Shareholders' Equity                          2009.0000  1909.0000   
Total Shareholders' Equity / Total Assets              0.8768     0.9125   
Total Equity                                        2009.0000  1909.0000   
Liabilities & Shareholders' Equity                  2291.0000  2092.0000   

                                                         2018  5-year trend  
Assets                                                                       
Fiscal year is July-June. All values BDT Millions.  2018.0000  5-year trend  
Cash & Short Term Investments                          8.0000           NaN  
Cash Only                                              8.0000           NaN  
Cash & Short Term Investments Growth                      NaN           NaN  
Cash & ST Investments / Total Assets                   0.0044           NaN  
...                                                       ...           ...  
Common Equity / Total Assets                           0.9118           NaN  
Total Shareholders' Equity                          1690.0000           NaN  
Total Shareholders' Equity / Total Assets              0.9118           NaN  
Total Equity                                        1690.0000           NaN  
Liabilities & Shareholders' Equity                  1854.0000           NaN  

[69 rows x 6 columns]

In [324]:
Total_Current_Assets=Balance_Sheet.loc['Total Current Assets',Balance_Sheet.columns][0:5].apply(lambda x :float(x)).values
Total_Current_Liabilities=Balance_Sheet.loc['Total Current Liabilities',Balance_Sheet.columns][0:5].apply(lambda x :float(x)).values
Cash_and_Cash_Equivalents=Balance_Sheet.loc['Cash Only',Balance_Sheet.columns][0:5].apply(lambda x :float(x)).values
Net_sales=Income_Satetment.loc['Sales/Revenue',Income_Satetment.columns][0:5].apply(lambda x :float(x)).values
Total_Assets=Balance_Sheet.loc['Total Assets',Balance_Sheet.columns][0:5].apply(lambda x :float(x)).values
Total_Accounts_Receivable=Balance_Sheet.loc['Total Accounts Receivable',Balance_Sheet.columns][0:5].apply(lambda x :float(x)).values
Total_Liabilities=Balance_Sheet.loc['Total Liabilities',Balance_Sheet.columns][0:5].apply(lambda x :float(x)).values
total_equity=Balance_Sheet.loc['Total Equity',Balance_Sheet.columns][0:5].apply(lambda x :float(x)).values
net_income=Income_Satetment.loc['Net Income Available to Common',Balance_Sheet.columns][0:5].apply(lambda x :float(x)).values

In [325]:
current_ratio=Total_Current_Assets/Total_Current_Liabilities#1.2 to 2 is considered as ideal current ration,which means the company has 2 time asset than its liabelities
current_ratio

array([4.72613065, 4.48725212, 5.6754386 , 8.44202899, 8.18852459])

In [326]:
cash_ratio=Cash_and_Cash_Equivalents/Total_Current_Liabilities#for every tk the company owes creditors in the next 12 months it has 0.5 in cash. 1 is considered to be the ideal cash ratio.
cash_ratio

array([0.04020101, 0.09065156, 0.12280702, 0.23188406, 0.06557377])

In [327]:
Total_Asset_turnover=Net_sales/Total_Assets
Total_Asset_turnover#each tk of assets generates 0.51 poisha in sales. The higher the ratio, the more efficient the company is using its assets to make sales.

array([0.60098696, 0.53813722, 0.51986032, 0.73661568, 0.74325782])

In [328]:
Account_receivable_turnover=Net_sales/Total_Accounts_Receivable
Account_receivable_turnover#A high-efficiency ratio means that the company has high-quality customers who pay their debts in due time.

array([2.84166667, 2.04366812, 1.96859504, 2.48949919, 2.39652174])

In [329]:
Debt_Ratio=Total_Liabilities/Total_Assets
Debt_Ratio#Debt financing

array([0.18047233, 0.15561518, 0.12309035, 0.0874761 , 0.08791802])

In [330]:
Equity_Ratio=total_equity/Total_Assets#Equity financed by owner. 0.5 tk means half of the firm financed by the owners and other half by creditors 
Equity_Ratio

array([0.81917519, 0.84476811, 0.87690965, 0.9125239 , 0.91154261])

In [331]:
Profit_margin_ratio=net_income/Net_sales#availability to generate net income, 10% means avg ,20 means high ,5% mean poor
Profit_margin_ratio

array([0.21935484, 0.17450142, 0.09823678, 0.14211551, 0.15602322])

In [332]:
ROE=net_income/total_equity
ROE

array([0.16092943, 0.11116152, 0.05823793, 0.11471975, 0.12721893])

In [333]:
ROA=net_income/Total_Assets
ROA

array([0.1318294 , 0.09390571, 0.0510694 , 0.10468451, 0.11596548])

In [334]:
fundamental=pd.DataFrame(columns=[Balance_Sheet.columns[0:5]],index=[[ ticker for i in range(9)],
                                                                ['current ratio','cash ratio','Total Asset turnover',
                                                                 'Account receivable turnover','Debt Ratio','Equity Ratio',
                                                                 'Profit margin ratio',
                                                                 'ROE','ROA']])
fundamental

2022 2021 2020 2019 2018
FORTUNE current ratio                NaN  NaN  NaN  NaN  NaN
        cash ratio                   NaN  NaN  NaN  NaN  NaN
        Total Asset turnover         NaN  NaN  NaN  NaN  NaN
        Account receivable turnover  NaN  NaN  NaN  NaN  NaN
        Debt Ratio                   NaN  NaN  NaN  NaN  NaN
        Equity Ratio                 NaN  NaN  NaN  NaN  NaN
        Profit margin ratio          NaN  NaN  NaN  NaN  NaN
        ROE                          NaN  NaN  NaN  NaN  NaN
        ROA                          NaN  NaN  NaN  NaN  NaN

In [335]:
fundamental.loc[ticker].loc['current ratio']=current_ratio
fundamental.loc[ticker].loc['cash ratio']=cash_ratio
fundamental.loc[ticker].loc['Total Asset turnover']=Total_Asset_turnover
fundamental.loc[ticker].loc['Account receivable turnover']=Account_receivable_turnover
fundamental.loc[ticker].loc['Debt Ratio']=Debt_Ratio
fundamental.loc[ticker].loc['Equity Ratio']=Equity_Ratio
fundamental.loc[ticker].loc['Profit margin ratio']=Profit_margin_ratio
fundamental.loc[ticker].loc['ROE']=ROE
fundamental.loc[ticker].loc['ROA']=ROA

In [336]:
fundamental

2022      2021      2020      2019  \
FORTUNE current ratio                4.726131  4.487252  5.675439  8.442029   
        cash ratio                   0.040201  0.090652  0.122807  0.231884   
        Total Asset turnover         0.600987  0.538137   0.51986  0.736616   
        Account receivable turnover  2.841667  2.043668  1.968595  2.489499   
        Debt Ratio                   0.180472  0.155615   0.12309  0.087476   
        Equity Ratio                 0.819175  0.844768   0.87691  0.912524   
        Profit margin ratio          0.219355  0.174501  0.098237  0.142116   
        ROE                          0.160929  0.111162  0.058238   0.11472   
        ROA                          0.131829  0.093906  0.051069  0.104685   

                                         2018  
FORTUNE current ratio                8.188525  
        cash ratio                   0.065574  
        Total Asset turnover         0.743258  
        Account receivable turnover  2.396522  
        Debt Ratio                   0.087918  
        Equity Ratio                 0.911543  
        Profit margin ratio          0.156023  
        ROE                          0.127219  
        ROA                          0.115965

In [337]:
df1=pd.read_excel("C:\\Users\\nafissaad\\Tutorial\\Fundamental analysis\\My Portfolio\\fundamental.xlsx",index_col=[0,1])
df1=df1.dropna(how='all',axis=0)
df1.columns=[i for i in fundamental.columns]
df1

(2022,)   (2021,)   (2020,)  \
RAKCERAMIC current ratio                1.661731  1.706442  1.671489   
           cash ratio                   0.159492  0.279715  0.357559   
           Total Asset turnover         0.519501  0.506578  0.422592   
           Account receivable turnover  7.262156  7.516461  5.242779   
           Debt Ratio                   0.426187  0.423613  0.438828   
...                                          ...       ...       ...   
APEXFOODS  Debt Ratio                   0.419355  0.531637  0.599183   
           Equity Ratio                  0.53871  0.433287  0.371645   
           Profit margin ratio          0.008255  0.004348  0.005037   
           ROE                          0.043413  0.019048  0.017268   
           ROA                          0.023387  0.008253  0.006418   

                                         (2019,)   (2018,)  
RAKCERAMIC current ratio                1.677189  1.560933  
           cash ratio                   0.354284  0.184449  
           Total Asset turnover         0.489099  0.512198  
           Account receivable turnover  5.583621  4.888884  
           Debt Ratio                   0.464541  0.475179  
...                                          ...       ...  
APEXFOODS  Debt Ratio                   0.578134  0.583868  
           Equity Ratio                 0.390969  0.388889  
           Profit margin ratio          0.007005  0.005203  
           ROE                          0.018237  0.013736  
           ROA                           0.00713  0.005342  

[378 rows x 5 columns]

In [338]:
df=pd.concat([df1,fundamental],axis=0)
df

(2022,)   (2021,)   (2020,)  \
RAKCERAMIC current ratio                1.661731  1.706442  1.671489   
           cash ratio                   0.159492  0.279715  0.357559   
           Total Asset turnover         0.519501  0.506578  0.422592   
           Account receivable turnover  7.262156  7.516461  5.242779   
           Debt Ratio                   0.426187  0.423613  0.438828   
...                                          ...       ...       ...   
FORTUNE    Debt Ratio                   0.180472  0.155615   0.12309   
           Equity Ratio                 0.819175  0.844768   0.87691   
           Profit margin ratio          0.219355  0.174501  0.098237   
           ROE                          0.160929  0.111162  0.058238   
           ROA                          0.131829  0.093906  0.051069   

                                         (2019,)   (2018,)  
RAKCERAMIC current ratio                1.677189  1.560933  
           cash ratio                   0.354284  0.184449  
           Total Asset turnover         0.489099  0.512198  
           Account receivable turnover  5.583621  4.888884  
           Debt Ratio                   0.464541  0.475179  
...                                          ...       ...  
FORTUNE    Debt Ratio                   0.087476  0.087918  
           Equity Ratio                 0.912524  0.911543  
           Profit margin ratio          0.142116  0.156023  
           ROE                           0.11472  0.127219  
           ROA                          0.104685  0.115965  

[387 rows x 5 columns]

In [339]:
Analysis.to_excel("C:\\Users\\nafissaad\\Tutorial\\Fundamental analysis\\My Portfolio\\Port_folio_draft.xlsx")
df.to_excel("C:\\Users\\nafissaad\\Tutorial\\Fundamental analysis\\My Portfolio\\fundamental.xlsx")

In [340]:
#clean Duplicate rows
df1=pd.read_excel("C:\\Users\\nafissaad\\Tutorial\\Fundamental analysis\\My Portfolio\\fundamental.xlsx",index_col=[0,1])
df1=df1.drop_duplicates()
df1.tail(30)

(2022,)    (2021,)    (2020,)  \
SIMTEX    Profit margin ratio           0.055476   0.054846   0.036944   
          ROE                            0.04321   0.042026   0.026316   
          ROA                           0.027441   0.027863   0.016635   
APEXFOOT  current ratio                 1.257388   1.134133   0.950131   
          cash ratio                    0.011159   0.010453   0.007111   
          Total Asset turnover          0.635967   0.668181   0.670756   
          Account receivable turnover   8.784699  13.114827  16.895565   
          Debt Ratio                    0.853544   0.835908   0.840291   
          Equity Ratio                  0.146456   0.164092   0.159709   
          Profit margin ratio           0.010636   0.008926   0.005334   
          ROE                           0.046185   0.036345   0.022404   
          ROA                           0.006764   0.005964   0.003578   
APEXFOODS current ratio                  1.79015   1.458616   1.330972   
          cash ratio                    0.008565   0.004071   0.003036   
          Total Asset turnover          2.833065   1.898212   1.274212   
          Account receivable turnover  11.187898   8.734177  11.805405   
          Debt Ratio                    0.419355   0.531637   0.599183   
          Equity Ratio                   0.53871   0.433287   0.371645   
          Profit margin ratio           0.008255   0.004348   0.005037   
          ROE                           0.043413   0.019048   0.017268   
          ROA                           0.023387   0.008253   0.006418   
FORTUNE   current ratio                 4.726131   4.487252   5.675439   
          cash ratio                    0.040201   0.090652   0.122807   
          Total Asset turnover          0.600987   0.538137    0.51986   
          Account receivable turnover   2.841667   2.043668   1.968595   
          Debt Ratio                    0.180472   0.155615    0.12309   
          Equity Ratio                  0.819175   0.844768    0.87691   
          Profit margin ratio           0.219355   0.174501   0.098237   
          ROE                           0.160929   0.111162   0.058238   
          ROA                           0.131829   0.093906   0.051069   

                                         (2019,)   (2018,)  
SIMTEX    Profit margin ratio             0.1049       NaN  
          ROE                           0.090746       NaN  
          ROA                           0.067496       NaN  
APEXFOOT  current ratio                 1.001496  1.005195  
          cash ratio                    0.015705  0.020582  
          Total Asset turnover          1.042879  1.111127  
          Account receivable turnover   7.787685  8.505600  
          Debt Ratio                    0.814566  0.808402  
          Equity Ratio                  0.185434  0.191598  
          Profit margin ratio            0.00778  0.008151  
          ROE                           0.043757  0.047273  
          ROA                           0.008114  0.009057  
APEXFOODS current ratio                 1.349087  1.293219  
          cash ratio                    0.011815  0.007641  
          Total Asset turnover          1.017825  1.026709  
          Account receivable turnover  13.926829  9.240385  
          Debt Ratio                    0.578134  0.583868  
          Equity Ratio                  0.390969  0.388889  
          Profit margin ratio           0.007005  0.005203  
          ROE                           0.018237  0.013736  
          ROA                            0.00713  0.005342  
FORTUNE   current ratio                 8.442029  8.188525  
          cash ratio                    0.231884  0.065574  
          Total Asset turnover          0.736616  0.743258  
          Account receivable turnover   2.489499  2.396522  
          Debt Ratio                    0.087476  0.087918  
          Equity Ratio                  0.912524  0.911543  
          Profit margin ratio         

In [341]:
#ceack whether there are duplicate index or not
[df1.index[i][0] for i in range(1,len(df1),9)]

['RAKCERAMIC',
 'SALAMCRST',
 'POWERGRID',
 'AFTABAUTO',
 'BATBC',
 'RENATA',
 'MARICO',
 'SINGERBD',
 'LINDEBD',
 'SUMITPOWER',
 'BERGERPBL',
 'BXPHARMA',
 'SQURPHARMA',
 'SAPORTL',
 'BSCCL',
 'GP',
 'SQUARETEXT',
 'EXIMBANK',
 'HEIDELBCEM',
 'OLYMPIC',
 'BSRMSTEEL',
 'BEXIMCO',
 'NATLIFEINS',
 'HFL',
 'BATASHOE',
 'APEXSPINN',
 'UPGDCL',
 'CROWNCEMNT',
 'BENGALWTL',
 'EHL',
 'IBNSINA',
 'WALTONHIL',
 'UNIQUEHRL',
 'UNILEVERCL',
 'KDSALTD',
 'JHRML',
 'ANDTEL',
 'ITC',
 'SIMTEX',
 'APEXFOOT',
 'APEXFOODS',
 'FORTUNE']

In [342]:
inx=idx = pd.Index([df1.index[i][0] for i in range(1,len(df1),9)])
idx.drop_duplicates(keep='first')

Index(['RAKCERAMIC', 'SALAMCRST', 'POWERGRID', 'AFTABAUTO', 'BATBC', 'RENATA',
       'MARICO', 'SINGERBD', 'LINDEBD', 'SUMITPOWER', 'BERGERPBL', 'BXPHARMA',
       'SQURPHARMA', 'SAPORTL', 'BSCCL', 'GP', 'SQUARETEXT', 'EXIMBANK',
       'HEIDELBCEM', 'OLYMPIC', 'BSRMSTEEL', 'BEXIMCO', 'NATLIFEINS', 'HFL',
       'BATASHOE', 'APEXSPINN', 'UPGDCL', 'CROWNCEMNT', 'BENGALWTL', 'EHL',
       'IBNSINA', 'WALTONHIL', 'UNIQUEHRL', 'UNILEVERCL', 'KDSALTD', 'JHRML',
       'ANDTEL', 'ITC', 'SIMTEX', 'APEXFOOT', 'APEXFOODS', 'FORTUNE'],
      dtype='object')

In [343]:
len(inx)

42

In [344]:
len(idx.drop_duplicates(keep='first'))

42