In [1]:
# this program predicts stock prices by  using machine learning models
# Install the dependencies
import yfinance as yf
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

In [2]:
#get the stock data
#load the data
df= yf.Ticker('META').history(start='2019-04-19',end='2022-10-14')
df.reset_index(inplace=True)
df

Date        Open        High         Low       Close    Volume  \
0   2019-04-18  178.800003  178.880005  177.339996  178.279999  11655600   
1   2019-04-22  178.250000  181.669998  178.250000  181.440002  13389900   
2   2019-04-23  182.740005  184.220001  181.479996  183.779999  19954800   
3   2019-04-24  184.490005  185.139999  181.649994  182.580002  37289900   
4   2019-04-25  196.979996  198.479996  192.119995  193.259995  54148800   
..         ...         ...         ...         ...         ...       ...   
875 2022-10-07  136.759995  138.289993  132.440002  133.449997  33179700   
876 2022-10-10  133.550003  136.110001  131.869995  133.789993  24024000   
877 2022-10-11  131.619995  132.660004  126.989998  128.539993  38481400   
878 2022-10-12  128.320007  129.669998  126.250000  127.500000  34605200   
879 2022-10-13  123.529999  131.139999  122.529999  130.289993  34297800   

     Dividends  Stock Splits  
0            0             0  
1            0             0  
2            0             0  
3            0             0  
4            0             0  
..         ...           ...  
875          0             0  
876          0             0  
877          0             0  
878          0             0  
879          0             0  

[880 rows x 8 columns]

In [3]:
#Get the Adjusted Close Price
df=df[['Close']]
#Take a look at the new data
print(df.head())

        Close
0  178.279999
1  181.440002
2  183.779999
3  182.580002
4  193.259995


In [4]:
#A variable for predicting
forecast_out= 30
#Create another column(the target or dependent variable) shift 'n' units up
df['Prediction']=df[['Close']].shift(-forecast_out)
#print the new data
print(df)

          Close  Prediction
0    178.279999  164.149994
1    181.440002  167.500000
2    183.779999  168.169998
3    182.580002  168.330002
4    193.259995  173.350006
..          ...         ...
875  133.449997         NaN
876  133.789993         NaN
877  128.539993         NaN
878  127.500000         NaN
879  130.289993         NaN

[880 rows x 2 columns]


C:\Users\nafissaad\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [5]:
#Create the indeoendent data set (x)
#Convert the dataframe to a numpy array
X=np.array(df.drop(['Prediction'],axis=1))
#Remove the last 'n' rows
X=X[:-forecast_out]
X

array([[178.27999878],
       [181.44000244],
       [183.77999878],
       [182.58000183],
       [193.25999451],
       [191.49000549],
       [194.77999878],
       [193.3999939 ],
       [193.02999878],
       [192.52999878],
       [195.47000122],
       [193.88000488],
       [189.77000427],
       [189.53999329],
       [188.6499939 ],
       [188.33999634],
       [181.53999329],
       [180.72999573],
       [186.27000427],
       [186.99000549],
       [185.30000305],
       [182.72000122],
       [184.82000732],
       [185.32000732],
       [180.86999512],
       [181.05999756],
       [184.30999756],
       [182.19000244],
       [183.00999451],
       [177.47000122],
       [164.1499939 ],
       [167.5       ],
       [168.16999817],
       [168.33000183],
       [173.3500061 ],
       [174.82000732],
       [178.1000061 ],
       [175.03999329],
       [177.47000122],
       [181.33000183],
       [189.00999451],
       [188.47000122],
       [187.47999573],
       [189

In [6]:
# Create the depencent data set (y)###
#Convert the dataframe to a numpy array(all of the values including the NaN's)
y=np.array(df['Prediction'])
# Get all of the y values except the last 'n' rows
y=y[:-forecast_out]
y

array([164.1499939 , 167.5       , 168.16999817, 168.33000183,
       173.3500061 , 174.82000732, 178.1000061 , 175.03999329,
       177.47000122, 181.33000183, 189.00999451, 188.47000122,
       187.47999573, 189.52999878, 191.13999939, 192.6000061 ,
       188.83999634, 187.66000366, 189.5       , 193.        ,
       193.        , 195.        , 197.19999695, 196.3999939 ,
       195.75999451, 199.21000671, 202.72999573, 201.22999573,
       204.86999512, 203.91000366, 203.83999634, 201.80000305,
       200.77999878, 198.36000061, 202.32000732, 202.36000061,
       204.66000366, 200.71000671, 199.75      , 195.94000244,
       197.03999329, 194.22999573, 192.72999573, 189.02000427,
       181.72999573, 184.50999451, 185.1499939 , 190.16000366,
       187.8500061 , 185.36999512, 188.44999695, 179.71000671,
       182.58999634, 183.69999695, 186.16999817, 183.80999756,
       183.55000305, 182.03999329, 177.75      , 180.36000061,
       181.30000305, 181.75999451, 185.57000732, 185.66

In [7]:
#Split the data into 80% training and 20% testing
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [8]:
#Create and train the Support Vector Machine (Regressor)
svr_rbf=SVR(kernel='rbf',C=1e3,gamma=0.1)
svr_rbf.fit(x_train,y_train)

SVR(C=1000.0, gamma=0.1)

In [9]:
svr_rbf.score(x_test,y_test)

0.6471385369804018

In [10]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [11]:
lr.score(x_test,y_test)

0.7303886759495112

In [12]:
x_forecast=np.array(df.drop(['Prediction'],axis=1))[-forecast_out:]
x_forecast

array([[165.36000061],
       [160.32000732],
       [158.53999329],
       [160.38999939],
       [162.05999756],
       [169.1499939 ],
       [168.96000671],
       [153.13000488],
       [151.47000122],
       [149.55000305],
       [146.28999329],
       [148.02000427],
       [146.08999634],
       [142.11999512],
       [142.82000732],
       [140.41000366],
       [136.36999512],
       [134.3999939 ],
       [141.61000061],
       [136.41000366],
       [135.67999268],
       [138.61000061],
       [140.27999878],
       [138.97999573],
       [139.07000732],
       [133.44999695],
       [133.78999329],
       [128.53999329],
       [127.5       ],
       [130.28999329]])

In [13]:
lr.predict(x_forecast)

array([172.35261972, 167.8232772 , 166.2236137 , 167.88617769,
       169.38697209, 175.75861191, 175.58787417, 161.36176387,
       159.86995133, 158.14448686, 155.21478041, 156.76950715,
       155.0350471 , 151.46728533, 152.09637249, 149.93054975,
       146.29987378, 144.52947256, 151.00896333, 146.33582867,
       145.6797822 , 148.31292252, 149.81371693, 148.64542983,
       148.72632148, 143.67572904, 143.98127704, 139.26320563,
       138.32858418, 140.8358961 ])