In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')
df=pd.read_csv('sonar_dataset.csv',header=None)
df.sample(5)

0       1       2       3       4       5       6       7       8   \
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
178  0.0197  0.0394  0.0384  0.0076  0.0251  0.0629  0.0747  0.0578  0.1357   
12   0.0079  0.0086  0.0055  0.0250  0.0344  0.0546  0.0528  0.0958  0.1009   
54   0.0132  0.0080  0.0188  0.0141  0.0436  0.0668  0.0609  0.0131  0.0899   
195  0.0129  0.0141  0.0309  0.0375  0.0767  0.0787  0.0662  0.1108  0.1777   

         9   ...      51      52      53      54      55      56      57  \
203  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
178  0.1695  ...  0.0134  0.0097  0.0042  0.0058  0.0072  0.0041  0.0045   
12   0.1240  ...  0.0176  0.0127  0.0088  0.0098  0.0019  0.0059  0.0058   
54   0.0922  ...  0.0044  0.0028  0.0021  0.0022  0.0048  0.0138  0.0140   
195  0.2245  ...  0.0124  0.0093  0.0072  0.0019  0.0027  0.0054  0.0017   

         58      59  60  
203  0.0193  0.0157   M  
178  0.0047  0.0054   M  
12   0.0059  0.0032   R  
54   0.0028  0.0064   R  
195  0.0024  0.0029   M  

[5 rows x 61 columns]

In [3]:
df.shape

(208, 61)

In [4]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [5]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [6]:
df[60]

0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: 60, Length: 208, dtype: object

In [7]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [8]:
x=df.drop(60,axis='columns')
y=df[60]
y.head()

0    R
1    R
2    R
3    R
4    R
Name: 60, dtype: object

In [9]:
y=pd.get_dummies(y,drop_first=True)
y.sample(5)

R
48  1
25  1
49  1
27  1
89  1

In [10]:
y.value_counts()

R
0    111
1     97
dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)

In [12]:
x_train.shape,x_test.shape

((156, 60), (52, 60))

In [13]:
import tensorflow as tf
from tensorflow import keras

In [14]:
model=keras.Sequential([
    keras.layers.Dense(60, input_dim=60,activation='relu'),
    keras.layers.Dense(30,activation='relu'),
    keras.layers.Dense(15,activation='relu'),
    keras.layers.Dense(1,activation='sigmoid'),
])
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=100,batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.6828 - accuracy: 0.5513
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6484 - accuracy: 0.6795
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6189 - accuracy: 0.7179
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5854 - accuracy: 0.6987
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5583 - accuracy: 0.7692
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5220 - accuracy: 0.7564
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4900 - accuracy: 0.8077
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4685 - accuracy: 0.7885
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4396 - accuracy: 0.7949
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4533 - accuracy: 0.7500
Epoch 11/

20/20 [==============================] - 0s 1ms/step - loss: 0.0048 - accuracy: 1.0000
Epoch 83/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0048 - accuracy: 1.0000
Epoch 84/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0050 - accuracy: 1.0000
Epoch 85/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0043 - accuracy: 1.0000
Epoch 86/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0039 - accuracy: 1.0000
Epoch 87/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0037 - accuracy: 1.0000
Epoch 88/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0037 - accuracy: 1.0000
Epoch 89/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 90/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0036 - accuracy: 1.0000
Epoch 91/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0036 - accuracy: 1.0000
Epoch 92/100


In [15]:
model.evaluate(x_test,y_test)

2/2 [==============================] - 0s 3ms/step - loss: 1.1258 - accuracy: 0.7500


[1.1258212327957153, 0.75]

In [16]:
y_pred=model.predict(x_test).reshape(-1)
print(y_pred[:10])
y_pred=np.round(y_pred)
print(y_pred[:10])

[1.0619314e-07 9.7927010e-01 9.8100972e-01 8.3035600e-05 1.0000000e+00
 9.9997675e-01 2.9876024e-02 1.0000000e+00 6.2434938e-06 1.0000000e+00]
[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]


In [17]:
model.predict(x_test)

array([[1.06193141e-07],
       [9.79270101e-01],
       [9.81009722e-01],
       [8.30356003e-05],
       [1.00000000e+00],
       [9.99976754e-01],
       [2.98760235e-02],
       [1.00000000e+00],
       [6.24349377e-06],
       [1.00000000e+00],
       [1.62369013e-03],
       [7.77488676e-05],
       [1.70707703e-04],
       [9.09358263e-04],
       [1.26489103e-02],
       [7.86181688e-02],
       [9.99986589e-01],
       [1.88618898e-04],
       [3.21841240e-03],
       [9.99994040e-01],
       [1.56879425e-04],
       [1.00000000e+00],
       [2.58174539e-03],
       [9.98087645e-01],
       [5.06848097e-04],
       [7.90982710e-07],
       [3.35721374e-02],
       [1.13756806e-01],
       [1.00000000e+00],
       [1.62434578e-03],
       [9.16529298e-01],
       [5.16837019e-07],
       [5.52035570e-02],
       [9.42119956e-03],
       [9.99804378e-01],
       [9.99637842e-01],
       [9.99999344e-01],
       [6.73184574e-01],
       [9.99989033e-01],
       [6.31809235e-04],


In [18]:
model.predict(x_test).reshape(-1)

array([1.06193141e-07, 9.79270101e-01, 9.81009722e-01, 8.30356003e-05,
       1.00000000e+00, 9.99976754e-01, 2.98760235e-02, 1.00000000e+00,
       6.24349377e-06, 1.00000000e+00, 1.62369013e-03, 7.77488676e-05,
       1.70707703e-04, 9.09358263e-04, 1.26489103e-02, 7.86181688e-02,
       9.99986589e-01, 1.88618898e-04, 3.21841240e-03, 9.99994040e-01,
       1.56879425e-04, 1.00000000e+00, 2.58174539e-03, 9.98087645e-01,
       5.06848097e-04, 7.90982710e-07, 3.35721374e-02, 1.13756806e-01,
       1.00000000e+00, 1.62434578e-03, 9.16529298e-01, 5.16837019e-07,
       5.52035570e-02, 9.42119956e-03, 9.99804378e-01, 9.99637842e-01,
       9.99999344e-01, 6.73184574e-01, 9.99989033e-01, 6.31809235e-04,
       6.27861619e-02, 2.37315893e-04, 5.60188293e-03, 2.24997511e-05,
       2.02706524e-05, 3.39269638e-04, 1.86967969e-01, 1.00000000e+00,
       3.77038121e-03, 3.87382507e-03, 4.37552035e-02, 9.48225716e-05],
      dtype=float32)

In [19]:
from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.71      0.89      0.79        27
           1       0.83      0.60      0.70        25

    accuracy                           0.75        52
   macro avg       0.77      0.74      0.74        52
weighted avg       0.77      0.75      0.74        52



In [20]:
modeld = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1, activation='sigmoid')
])

modeld.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

modeld.fit(x_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.7094 - accuracy: 0.5128
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7538 - accuracy: 0.4808
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7136 - accuracy: 0.4744
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6942 - accuracy: 0.5192
Epoch 5/100
20/20 [==============================] - 0s 1ms/step - loss: 0.7114 - accuracy: 0.4615
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7151 - accuracy: 0.5000
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6834 - accuracy: 0.5449
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6791 - accuracy: 0.5641
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6921 - accuracy: 0.5513
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6841 - accuracy: 0.5064
Epoch 11/

20/20 [==============================] - 0s 2ms/step - loss: 0.3096 - accuracy: 0.8590
Epoch 84/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3026 - accuracy: 0.8269
Epoch 85/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3539 - accuracy: 0.8846
Epoch 86/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2823 - accuracy: 0.8910
Epoch 87/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2948 - accuracy: 0.8782
Epoch 88/100
20/20 [==============================] - 0s 1ms/step - loss: 0.2481 - accuracy: 0.8910
Epoch 89/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2545 - accuracy: 0.8782
Epoch 90/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3244 - accuracy: 0.8462
Epoch 91/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2863 - accuracy: 0.8846
Epoch 92/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2455 - accuracy: 0.8846
Epoch 93/100


In [21]:
modeld.evaluate(x_test, y_test)

2/2 [==============================] - 0s 2ms/step - loss: 0.5334 - accuracy: 0.7308


[0.5334294438362122, 0.7307692170143127]

In [22]:
y_pred = modeld.predict(x_test).reshape(-1)
print(y_pred[:10])

# round the values to nearest integer ie 0 or 1
y_pred = np.round(y_pred)
print(y_pred[:10])

[2.1796945e-05 8.7809098e-01 7.4183410e-01 6.5411031e-03 9.9955434e-01
 9.1379857e-01 3.9774439e-01 9.9962270e-01 1.8390894e-02 9.9986243e-01]
[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]


In [23]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      0.89      0.77        27
           1       0.82      0.56      0.67        25

    accuracy                           0.73        52
   macro avg       0.75      0.72      0.72        52
weighted avg       0.75      0.73      0.72        52

