In [1]:
import numpy as np
A=np.array([[1,2,1],
           [4,4,5],
           [6,7,7]])
A

array([[1, 2, 1],
       [4, 4, 5],
       [6, 7, 7]])

In [2]:
inverse=np.linalg.inv(A)
inverse

array([[-7., -7.,  6.],
       [ 2.,  1., -1.],
       [ 4.,  5., -4.]])

In [3]:
#identity matrix
np.round(inverse@A)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [4]:
np.round(A@inverse)

array([[ 1., -0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])