In [1]:
import tensorflow as tf

In [2]:
daily_sales_number=[21,22,-108,31,-1,32,34,31]

In [3]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_number)
tf_dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [4]:
for sales in tf_dataset:
    #print(sales)
    print(sales.numpy())#convert tensor into a numpy object

21
22
-108
31
-1
32
34
31


In [5]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)


21
22
-108
31
-1
32
34
31


In [6]:
for sales in tf_dataset.take(3):
    print(sales.numpy())

21
22
-108


In [7]:
tf_dataset= tf_dataset.filter(lambda x: x>0)
for sales in tf_dataset:
    print(sales.numpy())

21
22
31
32
34
31


In [8]:
tf_dataset=tf_dataset.map(lambda x: x*72)
for sales in tf_dataset:
    print(sales.numpy())

1512
1584
2232
2304
2448
2232


In [9]:
tf_dataset=tf_dataset.shuffle(3)
for sales in tf_dataset:
    print(sales.numpy())

1512
2304
2232
2232
1584
2448


In [10]:
for sales in tf_dataset.batch(3):
    print(sales.numpy())

[2232 1512 1584]
[2448 2304 2232]


In [11]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_number)
tf_dataset=tf_dataset.filter(lambda x: x>0).map(lambda y: y*72).shuffle(2).batch(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1584 2232]
[1512 2304]
[2448 2232]


In [12]:
img=tf.data.Dataset.list_files('C:\\Users\\nafissaad\\Tutorial\\Deep Learning\\Codebasics\\ Deep learning project subject classification\\Subject\\*\\*',shuffle=False)
for file in img.take(3):
    print(file.numpy())

b'C:\\Users\\nafissaad\\Tutorial\\Deep Learning\\Codebasics\\ Deep learning project subject classification\\Subject\\Eng\\07b7b40ec437acca3389bcd5ebc577c3.jpg'
b'C:\\Users\\nafissaad\\Tutorial\\Deep Learning\\Codebasics\\ Deep learning project subject classification\\Subject\\Eng\\095b4413a7c4bd3fa1ec58510ac0ff6e.jpg'
b'C:\\Users\\nafissaad\\Tutorial\\Deep Learning\\Codebasics\\ Deep learning project subject classification\\Subject\\Eng\\12028b83a52dd172682d2b60ab00c090.jpg'


In [13]:
img_ds=img.shuffle(200)
for file in img_ds.take(3):
    print(file.numpy())

b'C:\\Users\\nafissaad\\Tutorial\\Deep Learning\\Codebasics\\ Deep learning project subject classification\\Subject\\Math\\09be8c92df9aa1050483e97f96bf98df.jpg'
b'C:\\Users\\nafissaad\\Tutorial\\Deep Learning\\Codebasics\\ Deep learning project subject classification\\Subject\\Math\\3453131da0264e48b0e79c53c15e4d30.jpg'
b'C:\\Users\\nafissaad\\Tutorial\\Deep Learning\\Codebasics\\ Deep learning project subject classification\\Subject\\Math\\6c6b4688535621bbbaf13ca062da419f.jpg'


In [14]:
class_names=['Eng','Math']

In [15]:
img_count=len(img_ds)
img_count

109

In [16]:
train_size=int(img_count*0.8)
train_ds=img_ds.take(train_size)
test_ds=img_ds.skip(train_size)

In [17]:
len(train_ds)

87

In [18]:
len(test_ds)

22

In [19]:
s='C:\\Users\\nafissaad\\Tutorial\\Deep Learning\\Codebasics\\ Deep learning project subject classification\\Subject\\Eng\\8f0d2bdd613bf43280131f534d5866a7.jpg'
s.split('\\')[-2]

'Eng'

In [20]:
def get_label(file_path):
    import os
    return(tf.strings.split(file_path,os.path.sep)[-2])

In [21]:
def process_image(file_path):
    label=get_label(file_path)
    img=tf.io.read_file(file_path)
    img=tf.image.decode_jpeg(img)
    img=tf.image.resize(img,[128,128])
    return img,label

In [22]:
for t in train_ds.take(4):
    print(t.numpy())

b'C:\\Users\\nafissaad\\Tutorial\\Deep Learning\\Codebasics\\ Deep learning project subject classification\\Subject\\Eng\\8f0d2bdd613bf43280131f534d5866a7.jpg'
b'C:\\Users\\nafissaad\\Tutorial\\Deep Learning\\Codebasics\\ Deep learning project subject classification\\Subject\\Eng\\6636d01726ed2b41fe98a7baa4845330.jpg'
b'C:\\Users\\nafissaad\\Tutorial\\Deep Learning\\Codebasics\\ Deep learning project subject classification\\Subject\\Eng\\3cf83c9c4d595679bf0bc9f13083b0b3.jpg'
b'C:\\Users\\nafissaad\\Tutorial\\Deep Learning\\Codebasics\\ Deep learning project subject classification\\Subject\\Eng\\439b81cab1c98bb92ea6fe20ec95f307.jpg'


In [23]:
train_ds=train_ds.map(process_image)
for label in train_ds.take(3):
    print('Image: ',img)
    print('Label: ',label)
    

Image:  <TensorSliceDataset shapes: (), types: tf.string>
Label:  (<tf.Tensor: shape=(128, 128, 3), dtype=float32, numpy=
array([[[153.5 , 136.5 , 108.5 ],
        [151.25, 134.25, 106.25],
        [152.5 , 135.5 , 107.5 ],
        ...,
        [162.5 , 145.5 , 119.5 ],
        [159.  , 142.  , 116.  ],
        [161.25, 144.25, 118.25]],

       [[150.  , 133.  , 105.  ],
        [151.5 , 134.5 , 106.5 ],
        [154.75, 137.75, 109.75],
        ...,
        [160.5 , 143.5 , 117.5 ],
        [160.25, 143.25, 117.25],
        [157.25, 140.25, 114.25]],

       [[149.25, 133.25, 107.25],
        [152.25, 136.25, 110.25],
        [158.75, 142.75, 116.75],
        ...,
        [163.75, 146.75, 120.75],
        [160.25, 143.25, 117.25],
        [162.  , 145.  , 119.  ]],

       ...,

       [[ 97.75,  85.25,  69.25],
        [ 99.  ,  86.  ,  70.  ],
        [ 99.  ,  86.  ,  70.  ],
        ...,
        [ 17.  ,  16.  ,  21.  ],
        [ 18.5 ,  17.5 ,  22.5 ],
        [ 17.75,  16.75, 

In [24]:
def scale(image,label):
    return image/255, label

In [25]:
train_ds=train_ds.map(scale)
for img,label in train_ds.take(5):
    print('Image: ', img.numpy()[0][0])
    print('Label: ', label.numpy())
    

Image:  [0.85882354 0.7607843  0.6745098 ]
Label:  b'Math'
Image:  [0.99607843]
Label:  b'Math'
Image:  [0.8241881  0.83203125 0.7771293 ]
Label:  b'Math'
Image:  [0.67117345 0.69862443 0.6672519 ]
Label:  b'Math'
Image:  [0.27156863 0.27941176 0.2754902 ]
Label:  b'Eng'
