In [1]:
import numpy as np
n=5
d=2
T=1.

In [2]:
times=np.linspace(0.,T,n)
times

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [3]:
dt=times[1]-times[0]
dt

0.25

In [4]:
np.sqrt(dt)#0.25**(1/2)

0.5

In [5]:
np.random.normal(size=(n-1))

array([-0.19646939, -0.47526122, -0.11199274,  2.78976941])

In [6]:
dB=np.sqrt(dt)*np.random.normal(size=(n-1))
dB

array([0.3178065 , 0.0414444 , 0.25808808, 0.12515287])

In [7]:
B0=np.zeros(shape=(1,))
B0

array([0.])

In [8]:
B=np.concatenate((B0,np.cumsum(dB)))
B

array([0.        , 0.3178065 , 0.3592509 , 0.61733898, 0.74249185])

In [9]:
dB=np.sqrt(dt)*np.random.normal(size=(n-1,d))
dB

array([[ 0.50796934,  0.78651806],
       [-0.13686103, -0.76644204],
       [ 0.17743027, -0.20598026],
       [-0.15834462,  0.09764869]])

In [10]:
B0=np.zeros(shape=(1,d))
B0

array([[0., 0.]])

In [11]:
B=np.concatenate((B0,np.cumsum(dB,axis=0)),axis=0)
B

array([[ 0.        ,  0.        ],
       [ 0.50796934,  0.78651806],
       [ 0.37110831,  0.02007602],
       [ 0.54853858, -0.18590424],
       [ 0.39019396, -0.08825555]])

In [12]:
np.diff(B,axis=0)

array([[ 0.50796934,  0.78651806],
       [-0.13686103, -0.76644204],
       [ 0.17743027, -0.20598026],
       [-0.15834462,  0.09764869]])

In [13]:
np.diff(B,axis=0,prepend=1.)


array([[-1.        , -1.        ],
       [ 0.50796934,  0.78651806],
       [-0.13686103, -0.76644204],
       [ 0.17743027, -0.20598026],
       [-0.15834462,  0.09764869]])

In [14]:
np.diff(B,axis=0,prepend=0.)

array([[ 0.        ,  0.        ],
       [ 0.50796934,  0.78651806],
       [-0.13686103, -0.76644204],
       [ 0.17743027, -0.20598026],
       [-0.15834462,  0.09764869]])

In [15]:
0.0929005*0.0929005*0.0929005

0.000801778034684675

In [16]:
np.power(np.diff(B,axis=0,prepend=0.),3)

array([[ 0.        ,  0.        ],
       [ 0.13107277,  0.48654846],
       [-0.00256354, -0.45023366],
       [ 0.00558577, -0.0087393 ],
       [-0.00397018,  0.00093111]])

In [17]:
np.cumsum(np.power(np.diff(B,axis=0,prepend=0.),2))

array([0.        , 0.        , 0.25803285, 0.87664351, 0.89537446,
       1.48280786, 1.51428936, 1.55671723, 1.58179025, 1.59132551])

In [18]:
np.cumsum(np.power(np.diff(B,axis=0,prepend=0.),2),axis=0)

array([[0.        , 0.        ],
       [0.25803285, 0.61861067],
       [0.27676379, 1.20604407],
       [0.30824529, 1.24847194],
       [0.33331831, 1.2580072 ]])

In [19]:
np.random.normal(size=(n-1))

array([ 0.76587384,  0.33718266, -0.89795912, -0.78889837])

In [20]:
np.random.normal(size=(n-1,2))

array([[ 1.07419609,  0.34345861],
       [ 0.11981496, -0.23297598],
       [-1.0885333 , -0.63015677],
       [ 1.06636556, -0.16233822]])

In [21]:
np.zeros(shape=(2,d))

array([[0., 0.],
       [0., 0.]])

In [22]:
np.cumsum([1,2,3,4],axis=0)

array([ 1,  3,  6, 10], dtype=int32)

In [23]:
np.linspace(0.,1,10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [24]:
np.random.normal(size=(10-1,4))


array([[ 0.62455842,  0.48413631, -1.69264043, -0.4772319 ],
       [ 0.7333011 ,  0.27375112,  1.91737037, -1.01282922],
       [-0.98910194, -0.81058367, -0.10026946, -1.17104376],
       [ 0.08436891, -0.2662842 ,  0.79001202,  0.45762102],
       [-0.9234    ,  0.90426943, -1.1542133 , -0.74306442],
       [-2.07758096,  1.94899859, -1.18504886, -0.49579255],
       [-0.16299434, -0.59484126, -0.76849035,  0.51043609],
       [ 0.27618608,  0.16326566, -0.25742002, -0.06635427],
       [ 0.2226703 , -0.18674003, -1.50838173,  0.66479999]])

In [25]:
np.zeros(shape=(1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
# Parameters
M = 10 # number of simulations
t = 10 # Time
random_walk = [-1, 1]#choice variation

In [27]:
np.random.choice(random_walk),np.random.choice(random_walk),np.random.choice(random_walk)

(1, 1, -1)

In [28]:
np.random.choice(random_walk,size=M)

array([-1, -1, -1,  1, -1, -1, -1, -1,  1, -1])

In [29]:
n=np.random.choice(random_walk,size=(M,t))
n

array([[-1,  1, -1, -1, -1,  1, -1,  1, -1,  1],
       [-1,  1, -1, -1, -1,  1, -1, -1,  1, -1],
       [-1, -1, -1,  1, -1, -1, -1,  1,  1, -1],
       [ 1, -1, -1, -1, -1,  1, -1, -1,  1,  1],
       [-1,  1,  1, -1, -1,  1,  1, -1,  1,  1],
       [ 1, -1, -1,  1,  1, -1,  1,  1, -1, -1],
       [-1,  1,  1, -1,  1,  1,  1,  1, -1, -1],
       [ 1,  1, -1,  1,  1,  1, -1,  1, -1, -1],
       [ 1, -1, -1, -1,  1,  1,  1,  1, -1,  1],
       [ 1, -1,  1,  1, -1, -1, -1,  1, -1, -1]])

In [30]:
O=n.T
O

array([[-1, -1, -1,  1, -1,  1, -1,  1,  1,  1],
       [ 1,  1, -1, -1,  1, -1,  1,  1, -1, -1],
       [-1, -1, -1, -1,  1, -1,  1, -1, -1,  1],
       [-1, -1,  1, -1, -1,  1, -1,  1, -1,  1],
       [-1, -1, -1, -1, -1,  1,  1,  1,  1, -1],
       [ 1,  1, -1,  1,  1, -1,  1,  1,  1, -1],
       [-1, -1, -1, -1,  1,  1,  1, -1,  1, -1],
       [ 1, -1,  1, -1, -1,  1,  1,  1,  1,  1],
       [-1,  1,  1,  1,  1, -1, -1, -1, -1, -1],
       [ 1, -1, -1,  1,  1, -1, -1, -1,  1, -1]])

In [31]:
k=np.zeros((1,M))
k

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
x=np.concatenate([k,O])
x

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1., -1.,  1., -1.,  1., -1.,  1.,  1.,  1.],
       [ 1.,  1., -1., -1.,  1., -1.,  1.,  1., -1., -1.],
       [-1., -1., -1., -1.,  1., -1.,  1., -1., -1.,  1.],
       [-1., -1.,  1., -1., -1.,  1., -1.,  1., -1.,  1.],
       [-1., -1., -1., -1., -1.,  1.,  1.,  1.,  1., -1.],
       [ 1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1., -1.],
       [-1., -1., -1., -1.,  1.,  1.,  1., -1.,  1., -1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1.,  1.,  1.,  1., -1., -1., -1., -1., -1.],
       [ 1., -1., -1.,  1.,  1., -1., -1., -1.,  1., -1.]])

In [33]:
x.cumsum(axis=0)#axis to run the operation in column wise oter waise, it consider x as a single dimensiom 

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1., -1.,  1., -1.,  1., -1.,  1.,  1.,  1.],
       [ 0.,  0., -2.,  0.,  0.,  0.,  0.,  2.,  0.,  0.],
       [-1., -1., -3., -1.,  1., -1.,  1.,  1., -1.,  1.],
       [-2., -2., -2., -2.,  0.,  0.,  0.,  2., -2.,  2.],
       [-3., -3., -3., -3., -1.,  1.,  1.,  3., -1.,  1.],
       [-2., -2., -4., -2.,  0.,  0.,  2.,  4.,  0.,  0.],
       [-3., -3., -5., -3.,  1.,  1.,  3.,  3.,  1., -1.],
       [-2., -4., -4., -4.,  0.,  2.,  4.,  4.,  2.,  0.],
       [-3., -3., -3., -3.,  1.,  1.,  3.,  3.,  1., -1.],
       [-2., -4., -4., -2.,  2.,  0.,  2.,  2.,  2., -2.]])

In [34]:
x.cumsum(axis=1)#axis to run the operation in row wise oter waise, it consider x as a single dimensiom 

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1., -2., -3., -2., -3., -2., -3., -2., -1.,  0.],
       [ 1.,  2.,  1.,  0.,  1.,  0.,  1.,  2.,  1.,  0.],
       [-1., -2., -3., -4., -3., -4., -3., -4., -5., -4.],
       [-1., -2., -1., -2., -3., -2., -3., -2., -3., -2.],
       [-1., -2., -3., -4., -5., -4., -3., -2., -1., -2.],
       [ 1.,  2.,  1.,  2.,  3.,  2.,  3.,  4.,  5.,  4.],
       [-1., -2., -3., -4., -3., -2., -1., -2., -1., -2.],
       [ 1.,  0.,  1.,  0., -1.,  0.,  1.,  2.,  3.,  4.],
       [-1.,  0.,  1.,  2.,  3.,  2.,  1.,  0., -1., -2.],
       [ 1.,  0., -1.,  0.,  1.,  0., -1., -2., -1., -2.]])

In [35]:
steps = np.random.choice(random_walk, size=(M,t)).T
origin = np.zeros((1,M))
rw_paths = np.concatenate([origin, steps]).cumsum(axis=0)

In [36]:
steps

array([[-1, -1, -1,  1,  1,  1, -1,  1, -1,  1],
       [ 1,  1, -1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1,  1, -1,  1,  1, -1, -1, -1],
       [-1,  1, -1, -1,  1,  1, -1, -1, -1,  1],
       [ 1,  1,  1,  1, -1, -1, -1,  1, -1,  1],
       [ 1,  1, -1, -1,  1, -1,  1,  1, -1, -1],
       [-1, -1,  1,  1, -1, -1,  1,  1, -1,  1],
       [-1, -1, -1, -1,  1,  1,  1, -1, -1,  1],
       [-1,  1, -1,  1, -1,  1, -1, -1, -1, -1],
       [ 1, -1, -1,  1, -1, -1, -1,  1,  1,  1]])

In [37]:
origin

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
rw_paths

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1., -1.,  1.,  1.,  1., -1.,  1., -1.,  1.],
       [ 0.,  0., -2.,  0.,  0.,  0., -2.,  2.,  0.,  2.],
       [ 1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.],
       [ 0.,  2., -2.,  0.,  0.,  2., -2.,  0., -2.,  2.],
       [ 1.,  3., -1.,  1., -1.,  1., -3.,  1., -3.,  3.],
       [ 2.,  4., -2.,  0.,  0.,  0., -2.,  2., -4.,  2.],
       [ 1.,  3., -1.,  1., -1., -1., -1.,  3., -5.,  3.],
       [ 0.,  2., -2.,  0.,  0.,  0.,  0.,  2., -6.,  4.],
       [-1.,  3., -3.,  1., -1.,  1., -1.,  1., -7.,  3.],
       [ 0.,  2., -4.,  2., -2.,  0., -2.,  2., -6.,  4.]])